- app/assets/stylesheets/hyku.scss
references #289 
CSS class that adds underlines to links when hovered was causing a unwanted dash after the repository images. This MR removes the CSS class that adds the underlines to these specific linked images
hovering over tenant images on the homepage will not add a small dash between images
> fix random dash on hover

- app/assets/stylesheets/hyku.scss
references #292 
Client asks for smaller headline size font on the splash page. Changed the fontsize to 22px to match BL font
> set splash header font size to 15pts 22px

- app/controllers/splash_controller.rb
references #291 
Accounts on homepage are sorting by name. Client would like the images on the homepage to sort by cname. There are tenants where the name is different from the cname and it is causing confusion
tenant images on the homepage sort alphabetically
> sort homepage by cname

- app/forms/hyrax/generic_work_form.rb
- app/forms/hyrax/image_form.rb
references: #294 
Places keyword before rights_statement on the GenericWork and Image forms
> reorder required fields in generic work and image

- config/locales/de.yml
- config/locales/en.yml
- config/locales/es.yml
- config/locales/fr.yml
- config/locales/it.yml
- config/locales/pt-BR.yml
- config/locales/zh.yml
references: #290 
Updates the hint/helper text for the Directory Image. Image width should be 2x the height or less
> updates hint text for directory image

- app/presenters/hyku/work_show_presenter.rb
- app/presenters/hyrax/etd_presenter.rb
- app/presenters/hyrax/oer_presenter.rb
- app/views/hyrax/base/show.html.erb
ref: #268 
This PR does a few things:
- remove "Generic Work" from the page titles (so it will not show in the browser tab, search results)
- remove "Generic Work" for the work show page
- Upcases OER and ETD on page titles (browser tab, search results)
Browser tab and search results will show updated text as per client
> I268 worktype labels

- .github/workflows/build-test-lint.yaml
- app/controllers/hyrax/contact_form_controller.rb
- app/models/hyrax/contact_form.rb
Ref Ticket: https://github.com/scientist-softserv/palni-palci/issues/279
We have html required: true on each form field.
Removing the validations from the controller allows the user to submit their fields while robot fields left unfilled will not give the user a validation error.
But when the robot fills out the negative captcha form fields that are not visible to the user will not be able to submit the form and an error will appear with the captcha error.
> remove-form-validations-as-they-conflict-with-negative-captcha

- app/views/records/edit_fields/_default.html.erb
fixes #185 rework
-Uses f.object.model instead of `@collection || curation_concern` as neither of those existed with batch edits. This allows for custom labels for different worktypes that use the same property. 
-Updated the code comment for override to use the correct location of the original partial
Selecting multiple works and choosing edit from the admin dashboard should not throw error.
> uses f.object.model in form partial

- app/services/hyrax/solr_query_service_decorator.rb
ref: #334 
Error occurs when visiting the review submissions section of admin dashboard: `RSolr::Error::Http - 414 Request-URI Too Long
Error: reason: URI Too Long`
This MR changes the get request to a post request. Post requests to solr allow for 2MB while get requests 8192 bytes. Using the post request should make no difference to solr.
When there are a lot of items on the review submissions tab, you should not receive an error that the query request is too long.
This error only occurs when there are a lot of items to display on the review submissions tab
> try using a post request to solr to increase query size

- app/assets/stylesheets/themes/cultural_repository.scss
ref: #337 
When cultural repo is selected, the panel header color overrides the workflow actions panel. This adds CSS to the cultural repository them to prevent that override.
When cultural repo is selected, the workflow actions panel has a gold background color
> workflow actions header color

- app/views/hyrax/admin/appearances/show.html.erb
ref: #149 
Needed to run migrations on staging in order to get the favicons to save. This mr unhides the favicon tab
> show favicon tab

- app/models/solr_endpoint.rb
Adds the connection to the blacklight.yml instead of using the cached values
> fix-solr-bl-adapter-issue

- ops/demo-deploy.tmpl.yaml
- ops/production-deploy.tmpl.yaml
`HYKU_CONTACT_EMAIL` needed to be set with an email from the approved domain set in AWS SES.
> add-email-from

- config/initializers/hyrax.rb
set require files to false
refs #406 Pals wants to allow users to upload works without files.  Setting `config.work_requires_files = false` removes the `File` requirement on the `New Work Form` in the UI.
<details><summary>Before code changes:</summary>
<details><summary>After code changes:</summary>
> i406-create-work-no-files 

- Gemfile
- Gemfile.lock
- app/models/active_fedora/base_decorator.rb
- app/models/concerns/order_metadata_values.rb
- app/models/etd.rb
- app/models/generic_work.rb
- app/models/image.rb
- app/models/oer.rb
- spec/models/concerns/order_metadata_values_spec.rb
- spec/models/etd_spec.rb
- spec/models/generic_work_spec.rb
- spec/models/image_spec.rb
- spec/models/oer_spec.rb
- spec/support/shared_examples.rb
Ref https://github.com/scientist-softserv/palni-palci/issues/401
Apply `OrderAlready` gem to all multi-valued properties in all work types 
All properties that allow multiple values will display those values in the same order that they were inputted in the form
> i401 Add OrderAlready gem to all multi-valued metadata properties

- app/controllers/catalog_controller.rb
- app/forms/hyrax/etd_form.rb
- app/forms/hyrax/generic_work_form.rb
- app/forms/hyrax/image_form.rb
- app/forms/hyrax/oer_form.rb
- app/indexers/etd_indexer.rb
- app/indexers/generic_work_indexer.rb
- app/indexers/image_indexer.rb
- app/indexers/oer_indexer.rb
- app/models/etd.rb
- app/models/generic_work.rb
- app/models/image.rb
- app/models/oer.rb
- app/models/solr_document.rb
- app/presenters/hyku/work_show_presenter.rb
- app/views/hyrax/base/_attribute_rows.html.erb
- app/views/hyrax/etds/_attribute_rows.html.erb
- app/views/hyrax/oers/_attribute_rows.html.erb
- config/locales/blacklight.en.yml
- config/locales/etd.en.yml
- config/locales/generic_work.en.yml
- config/locales/image.en.yml
- config/locales/oer.en.yml
- config/locales/simple_form.en.yml
add admin note to all work types
refs #405. Pals wants to add a new field on the `new/edit work form` called `Administrative Note`. This should sit towards the top of the form, but below all the required fields. Only those with edit access should be able to see this field on the work show page.
<details><summary>Users with edit access can see "Administrative Note" on new/edit work form for all 4 work types. This field is at the top of the form, but below the required fields</summary>
</details>
<details><summary>With UV: Users with edit access can see "Administrative Note" on work show page</summary>
</details>
<details><summary>Without UV: Users with edit access can see "Administrative Note" on work show page</summary>
</details>
<details><summary>Users without edit access cannot see …
> i405-admin-notes

- app/renderers/hyrax/renderers/attribute_renderer_decorator.rb
- app/views/hyrax/base/_work_description.erb
- app/views/hyrax/dashboard/collections/_collection_title.html.erb
Fixes a few places where markdown was not rendering correctly
Refs #402 
<details>
<summary> Hyperlinks in description </summary>
</details>
<details>
<summary> Hyperlinks in abstracts </summary>
</details>
<details>
<summary> Dashboard titles </summary>
</details>
> Rework for markdown

- lib/oai/provider/metadata_format/hyku_dublin_core.rb
Avoids `414 Request-URI Too Long` errors when works have many file sets
Refs #423 #440 
Works with many file sets cause OAI pages to throw errors 
Works with many file sets (<= 1024) do not cause OAI pages to throw errors 
Works that have more than 1024 could still throw errors
> use POST to increase request size limit

- app/assets/stylesheets/hyku.scss
- app/forms/hyrax/forms/admin/appearance.rb
- app/helpers/application_helper.rb
- app/views/hyrax/admin/appearances/_color_input.html.erb
- app/views/shared/_appearance_styles.html.erb
- config/locales/en.yml
- spec/views/hyrax/admin/appearances/show.html.erb_spec.rb
- Refs #449 
<details>
<summary> color form BEFORE</summary>
</details>
- better named color labels
- help text where useful
<details>
<summary>color form AFTER</summary>
</details>
<details>
<summary> fuller notes </summary>
color changes only apply to the public page, not the admin dashboard
- header and footer background color on every public page
- text color of all text/links in the header
- notification bell
- user icon
- color of all non linked text in the footer
- nav bar background (40% opacity of the color chosen)
- active link background on the navbar color ONLY. darker version of the chosen color. it's a hex and not an rgba so I can't figure out how it's set
- does not affect the bg color of the other navbar links. those are blue unless overridden with css
- bg color of nav …
> 449 color labels

- app/controllers/hyrax/admin/analytics/collection_reports_controller_decorator.rb
while diem was testing this feature on staging, she deleted a collection and [received a 500 error](https://assaydepot.slack.com/archives/G0311DNF3MG/p1684188070243439) on the collections analytics page. according to the rancher logs and sentry, we were getting an "ldp gone" error.
- Refs #408
- we were accounting only for an "object not found" error when looking up collections
- account for all errors that can happen if a collection can't be found for some reason
<details>
<summary>proof of concept in terminal</summary>
</details>
> 408 ldp gone

- app/models/concerns/account_settings.rb
Adds only the setting for allowing downloads. the actual places where downloads can need to be turned on & off will be in the next pr. 
- #468 
<details>
<summary>Setting in dashboard</summary>
</details>
<details>
<summary>Setting in proprietor area</summary>
</details>
> Allow downloads setting

- app/presenters/hyku/menu_presenter.rb
- app/views/hyrax/dashboard/sidebar/_configuration.html.erb
- config/features.rb
Refs #447 
- in the admin dashboard on the sidebar the workflow roles displays
- in the admin dashboard sidebar under the configuration section of the sidebar, in settings > features, you see a feature flipper to flip the feature of displaying the workflow roles menu item on the admin dashboard sidebar on/off
- in the admin dashboard on the sidebar the workflow roles menu item displays the menu item if the feature flipper is set to on
- in the admin dashboard on the sidebar the workflow roles menu item does not display if the feature flipper is set to off
<details>
<summary>CLICK ME FOR SCREENSHOTS OF IMPLEMENTATION</summary>
</details>
> add the feature flipper

- app/models/concerns/account_settings.rb
- config/analytics.yml
`HYRAX_ANALYTICS=true` is still set in the staging and prod environments so that the client doesn't miss any tracking. therefore, all the analytics partials still try to load. although the [config](https://github.com/scientist-softserv/palni-palci/blob/main/app/services/hyrax/analytics/google.rb#L28) got set initially, once we went through the hyku account settings, each config property [was set to an empty string](https://github.com/scientist-softserv/palni-palci/blob/main/app/models/concerns/account_settings.rb#L75-L80). so when the dashboard tried to load the user graph, the config was [invalid](https://github.com/scientist-softserv/palni-palci/blob/main/app/services/hyrax/analytics/google.rb#L113).
we need for the app to still be able to read from the env variables, (old way) while …
> 408-three-fold-approach

- app/views/hyrax/admin/workflows/index.html.erb
Show the user that is the depositor by their display name if there is one, or leave blank.
Refs #444 
The Workflow Review page at app/views/admin/workflows/index.html.erb display's the works' creators metadata
The Workflow Review page at app/views/admin/workflows/index.html.erb display's the depositors display name if there is one, leave blank.
<details>
<summary>CLICK FOR SCREENSHOTS OF WORK IN LOCAL DEV</summary>
Work:
Before:
After with display_name:
After no display_name:
</details>
> 444-show-depositors-not-creators-under-depositor-column-review-tab

- app/views/hyrax/file_sets/_actions.html.erb
- app/views/hyrax/file_sets/media_display/_audio.html.erb
- app/views/hyrax/file_sets/media_display/_default.html.erb
- app/views/hyrax/file_sets/media_display/_image.html.erb
- app/views/hyrax/file_sets/media_display/_office_document.html.erb
- app/views/hyrax/file_sets/media_display/_pdf.html.erb
- app/views/hyrax/file_sets/media_display/_video.html.erb
wraps download links in an `if` statement that checks if `allow_downloads` is disabled
> Restrict downloads

- README.md
- app/models/concerns/account_settings.rb
- config/locales/simple_form.en.yml
I thought that the google and matomo variable names were the same, so I made all of the google analytics variables be generic. looking at the [hyrax analytics config](https://github.com/samvera/hyrax/blob/main/.dassie/config/analytics.yml) shows this not to be the case.
Refs:
- #408 
- #409 
- google analytics variable names were generic
- return the "google" prefix to the google only analytics variable names
- update related form hints
> 408-return-google-prefix

- app/models/concerns/account_settings.rb
- config/analytics.yml
- config/locales/simple_form.en.yml
Refs
- #408 
- #409 
- without setting tenant level account settings, the dashboard would load fine
- after adding and saving the account settings, the dashboard would err
- this is because the user graph needs the correct [profile](https://github.com/scientist-softserv/palni-palci/blob/main/app/services/hyrax/analytics/google.rb#L112-L119). `Hyrax::Analytics.config.valid?` would return false however. while `Hyrax.config.analytics` would be true. (this may be a side effect of trying to have a fallback only, since `HYRAX_ANALYTICS=true` is set in the ENV variables)
- either way, the correct settings would be set on the `Account.settings` object. 
- usw `self` to make sure that everything gets set properly when reloading the analytics properties
- a user is able to see analytics related …
> 408-for-the-last-time

- app/presenters/hyku/work_show_presenter.rb
- app/views/hyrax/base/_items.html.erb
- lib/oai/provider/model_decorator.rb
Show page was getting an error 
```
private method `solr_document' called for #<Hyrax::IiifAv::IiifFileSetPresenter:0x0000ffff99dab0f8>
Did you mean?  solr_document=
```
Refs #507 
This was hitting old code from our previous attempt at splitting PDFs that was partially removed. This removes old code referencing "is_derived" files.
Show page hits error
Show page does not error
This was found on staging when a user is logged out.
> I507 show page error

- app/services/hyrax/contributing_library_service.rb
- app/views/records/edit_fields/_contributing_library.html.erb
- config/authorities/contributing_libraries.yml
Makes contributing library into a controlled vocab
- #495
Contributing library was a regular field
Contributing library is a controlled vocab, with 3 options - Contributing Library 1, Contributing Library 2, & Contributing Library 3
https://share.getcloudapp.com/12ukBJ9W
- ids/terms of contributing libraries will need to be filled in: ticket for that below
- https://github.com/scientist-softserv/palni-palci/issues/511
> Controlled vocab for contributing library

- app/views/shared/_footer.html.erb
- config/locales/hyrax.de.yml
- config/locales/hyrax.en.yml
- config/locales/hyrax.es.yml
- config/locales/hyrax.fr.yml
- config/locales/hyrax.it.yml
- config/locales/hyrax.pt-BR.yml
- config/locales/hyrax.zh.yml
In the footer update the 2019 Samvera copyright date to say 2019-2023 (with 2023 set to the current year).
- https://github.com/scientist-softserv/palni-palci/issues/531
> Use current year

- app/forms/hyrax/forms/admin/appearance.rb
- app/views/shared/_appearance_styles.html.erb
- config/locales/en.yml
Enables updating the collection title text color
- #518 
- collection title was set to white no matter what, making it hard to see if you don't add a banner
- users can update the collection title/last updated text from the appearance styles "Collection Banner Text Color" setting
https://share.getcloudapp.com/X6u7rA24
> Collection name display

- app/assets/stylesheets/hyku.scss
#525 - On the facets on the search results page, the number of items that are available under a given heading are not justified and move around depending upon the length of the word or phrase from the facet.
#526 - The X to remove filters can be hard to see for many users. Change the color to make it more clear.
- https://github.com/scientist-softserv/palni-palci/issues/525
- https://github.com/scientist-softserv/palni-palci/issues/526
Facet count justification
X is now red
> Facet count justification & filter x color

- app/views/catalog/_index_gallery_collection_wrapper.html.erb
Refs #520 
When the gallery view is selected on the Search results page, the default collection thumbnail shows up when there is a collection thumbnail added to the collection.
Switching to use the render_thumbnail_tag fixes this and probably fixes the issue with shared search as well
Default thumbnail shows instead of collection thumbnail when you are using the gallery view
Collection thumbnail shows up on the gallery view
<details>
</details>
> Switches thumbnail method for gallery view partial

- app/helpers/hyrax/citations_behaviors/formatters/apa_formatter.rb
- app/views/catalog/_index_gallery_collection_wrapper.html.erb
- app/views/hyrax/base/_citations.html.erb
Client requests updates to the Citations dropdown on the work show page
Refs #534 
Citations did not have editions, MLA link had http/https, APA did not use creator initials
Updated Citations with Editions, add periods, remove http/https from MLA link, use initials on APA
> I534 citation editions

- app/assets/stylesheets/hyku.scss
- app/views/catalog/_index_gallery_collection_wrapper.html.erb
- config/locales/blacklight.de.yml
- config/locales/blacklight.en.yml
- config/locales/blacklight.es.yml
- config/locales/blacklight.fr.yml
- config/locales/blacklight.it.yml
- config/locales/blacklight.pt-BR.yml
- config/locales/blacklight.zh.yml
Refs #522 
The start over button was confusing to users. Changed the text to "New Search" and make the font a little bigger and bolder.
Start over link was small
Start over link is a bit bigger and now says "New Search"
<details>
<summary>New Search button</summary>
</details>
> I522 start over button

- app/views/catalog/_index_gallery_collection_wrapper.html.erb
- spec/forms/hyrax/forms/permission_template_form_spec.rb
- spec/models/etd_spec.rb
- spec/views/hyrax/oers/_attribute_rows.html.erb_spec.rb
#548 
Fixes some specs
- based_near is not on ETD worktype so removed from ETD spec
- Changed permission template spec to match Hyku
- OER attribute rows added a can? ability so modified the test to account for that
specs fail in CI
specs pass in CI
<details>
</details>
> I548 fix specs

- app/assets/stylesheets/hyku.scss
- app/views/hyrax/collections/show.html.erb
- app/views/shared/_appearance_styles.html.erb
- spec/rails_helper.rb
- spec/support/spec_statistic.rb
- Edits to the collection:show page
- #523
- #528
- #529
- https://github.com/scientist-softserv/palni-palci/issues/541
- [figma project](https://www.figma.com/file/mBmGMQCeoBNWhrsZmvCkvh/Pals-Collection-Show-Page?type=design&node-id=0-1&t=rGlmwNZt0iLc46tc-0)
<details>
<summary>Logged out</summary>
</details>
<details>
<summary>Logged in</summary>
</details>
> change the layout for the collection show page

- spec/features/admin_dashboard_spec.rb
- spec/features/collection_reader_role_spec.rb
- spec/features/feature_flag_spec.rb
- spec/rails_helper.rb
- spec/support/spec_statistic.rb
Fixes several more specs that were failing, or comments out temporarily if the actual functionality of what it is testing is working correctly. 
- `collection_role_manager_spec.rb`
- `feature_flag_spec`
- `admin_dashboard_spec`
- #548
> Fix more specs

- config/tinymce.yml
- Adds the source code option to content editor
- The ticker said they also wanted images, but this had been added already
- #205 
- Could not edit source code of content blocks/custom pages
- Can edit source code in the wysiwyg editor for all of the content blocks/custom pages
Video: https://github.com/scientist-softserv/palni-palci/pull/new/205-improved-text-editing
<details>
<summary>Custom pages will have the same editor options</summary>
</details>
> Add source code editing to content editor

- app/assets/stylesheets/hyku.scss
- app/views/catalog/_index_gallery_collection_wrapper.html.erb
- app/views/splash/index.html.erb
Consortia logos on the Splash page will be links to institutions home pages
Refs #376 
consortia logos were not links
consortia logos are linked
> I376 consortia links

- config/locales/blacklight.de.yml
- config/locales/blacklight.en.yml
- config/locales/blacklight.es.yml
- config/locales/blacklight.fr.yml
- config/locales/blacklight.it.yml
- config/locales/blacklight.pt-BR.yml
- config/locales/blacklight.zh.yml
fix nesting issue in locale files
Refs #567
The locale files had an extra `search`, which broke some nesting. The original `search` is on lines 4/5 of these files. The extra `search` broke locales on the search page:
- facets
- search results
- locales are broken for search page:
- facets
- search results
- locales are fixed for search page:
- facets
- search results
<details>
<summary>Before changes: search page's facets and results had broken locales</summary>
</details>
<details>
<summary>After changes: search page's facets and results locales are fixed. I also checked to make sure that the "New Search" text is correct in all languages</summary>
</details>
> i567-creator-label-missing

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/stylesheets/application.css
- app/assets/stylesheets/hyku.scss
- app/controllers/catalog_controller.rb
- app/controllers/search_history_controller.rb
- app/indexers/app_indexer.rb
- app/indexers/etd_indexer.rb
- app/indexers/oer_indexer.rb
- app/models/etd.rb
- app/models/generic_work.rb
- app/models/image.rb
- app/models/oer.rb
- app/models/search_builder.rb
- app/presenters/hyku/work_show_presenter.rb
- app/views/blacklight_range_limit/_range_limit_panel.html.erb
- config/environments/development.rb
- config/locales/blacklight.en.yml
- config/locales/hyrax.en.yml
- config/routes.rb
Adds a facet for date created
- #519 
- there was no facet for date/date created
<details>
<summary>Working date facet</summary>
</details>
Video: 
https://share.getcloudapp.com/yAu9LWGY
- All works will need to be reindexed in order to have a date that can be sorted.
> Date Facet

- app/models/concerns/account_settings.rb
- config/analytics.yml
use the default analytics as a default on prod only.
the per tenant analytics work was already merged to main and the defaults were hidden on staging. however, pals wants to hold off on deploying that code to production until the ga4 switch has happened so both major changes can happen at the same time.
putting the analytics defaults in a conditional ensures that we can still deploy to production from main.
related to:
- https://github.com/scientist-softserv/palni-palci/issues/569
- #487
> hide-per-tenant-analytics-on-prod

- config/analytics.yml
default the env variables in analytics.yml to be empty strings so they do not fail when the env variable is not present
ref:
- #579 
- [slack thread](https://assaydepot.slack.com/archives/C0311DNF3MG/p1687473554171879) outlining the issue that this pr solves
> add-analytics-yml-fallback

- app/models/etd.rb
- app/models/generic_work.rb
- app/models/image.rb
- app/models/oer.rb
- app/views/hyrax/base/_attribute_rows.html.erb
- config/locales/hyrax.en.yml
Rework for the Based Near (Location) field
- #530 
- 
- Deleting items from the `based_near` field was not working.
- The field was still being called Based Near in the form.
- enables users to be able to delete values from the `based_near` field
- The label for the field in the edit form is now "Location" instead of "Based Near"
- the label for Location is now bold on the work show page for default theme
> 530 - Rework for based_near

- app/services/hyrax/solr_query_service_decorator.rb
- app/services/hyrax/workflow/permission_query.rb
- app/views/hyrax/admin/workflows/index.html.erb
Pals had some Hyrax files overridden that were changed with the recent Hyrax upgrade. This updates the Hyrax files and keeps our local changes
Workflow index has 500 error
Workflow index is loading
<details>
</details>
> fix bug with workflow pagination - updates overridden hyrax files

- app/services/hyrax/manifest_builder_service_decorator.rb
- app/views/themes/reshare_show/hyrax/base/iiif_viewers/_universal_viewer.html.erb
- config/uv/uv-config-reshare.json
- config/uv/uv.html
Customize the UV for ReShare
- #600
- UV should not have buttons for download or share
- UV should have 2 page view enabled
Video showing 2 page view: 
https://share.getcloudapp.com/4guXlO1n
<details>
<summary>UV in ReShare Show Theme</summary>
</details>
Originally we were going to use an account setting for this, but since there are other customizations they want that didn't make a ton of sense anymore and it seemed better do it in the theme. See this for details. 
- #608
> I600 uv customization

- app/models/etd.rb
- app/models/generic_work.rb
- app/models/image.rb
- app/models/oer.rb
Reverts part of a rework pr that was doing nothing. The `allow_destroy` functionality still does not work on initial load so this will need to be fixed in a different way. 
- PR this is reverting - https://github.com/scientist-softserv/palni-palci/pull/596
- The 2 additional changes in the pr above (updating locale for location, & updating attribute rows to make the location a dl) should remain. 
- Original ticket this was trying to fix: #530
> Reverts change for 530rework that was doing nothing

- app/controllers/auth_providers_controller.rb
- app/models/concerns/account_settings.rb
@labradford  @sephirothkod 
Should make the auth providers actually only have one auth provider. 
Adds a setting so the tenant has the id of the auth provider saved
Will need to delete the existing auth providers from staging tenants so this functions correctly
> More sso rework

- app/controllers/auth_providers_controller.rb
Bug rework
Refs #496
Deleting an auth provider caused an error when accessing the auth provider page
Deleting an auth provider does not throw error
<details>
</details>
Will need to manually reset auth_provider in the broken tenant
> remove auth provider from account settings on delete

- Dockerfile
- Gemfile.lock
- app/models/auth_provider.rb
- app/models/generic_work.rb
- app/services/hyrax/manifest_builder_service_decorator.rb
- app/views/hyrax/admin/workflows/index.html.erb
- config/routes.rb
- spec/features/advanced_search_spec.rb
- spec/models/auth_provider_spec.rb
- spec/presenters/hyrax/oer_presenter_spec.rb
- spec/rails_helper.rb
- spec/search_builders/adv_search_builder_spec.rb
Resolves merge conflicts from merging main into reshare feature. fixes selenium issue with spec suite, and remaining failing specs
#634
> Fix spec issues, resolve merge conflicts for reshare feature

- Gemfile.lock
From Bulkrax commit:
> Prior to this commit, when exporting a FileSet and GenericWork we'd
> see a "creator_1" and "creator" column.  The "creator" column might
> look as follows: `["Sandra Samvera"]`.  Which meant that creator was
> not an `ActiveTriples::Relation` (based on the prior logic).  Yet the
> "creator" field was stored as multi-value.  Perhaps having been
> previously coerced into an Array.
>
> With this commit, we're favoring the Bulkrax parser field mapping
> `"join"` configuration over whether or not the object is an
> =ActiveTriples::Relation=.  That is to say, if you told us to join the
> field, we're going to do that regardless of the data we have.
>
> Likewise, if the field's value is not an enumerable, we're not going
> to introduce an ordinal suffix (e.g. "creator_1" …
> 🐛 Buping Hyrax to resolve CSV export

- app/models/work_authorization.rb
- db/migrate/20230804202804_add_work_authorizations.rb
- db/schema.rb
- spec/models/work_authorization_spec.rb
**_Note:_ This is the "how do we give and revoke access" not the "when do I give and revoke"; that is something determined during user authentication and is partially dependent on the SSO work.  However, this highlights the underlying logic to authorize and revoke user's read rights for given works.**
98cc8aad6aa3e4c4ef59cea6169669aa888b64d7
With this commit, we're adding a mechanism to "lend" folks books.  This
change accounts for granting a user read rights to a work.
It does not introduce the logic/functionality that "authorizes" or
"revokes" this loaned resource.  With this commit, there are no changed
production logic paths.
Related to:
- https://github.com/scientist-softserv/palni-palci/issues/633
Co-authored-by: Summer Cook <summer@scientist.com> …
> 🎁 Adding WorkAuthorization model for CDL

- app/controllers/api/sushi_controller.rb
- config/application.rb
- config/routes.rb
- spec/requests/sushi_spec.rb
- #622 
- #648 
<details>
<summary>Current behavior for each route
</summary>
</details>
> Build JSON Reports

- app/controllers/identity_providers_controller.rb
when creating or updating an IdentityProvider, display an error if the JSON does not parse instead of throwing an exception
> error handling for json

- app/controllers/api/sushi_controller.rb
- app/models/sushi/report_list.rb
- config/routes.rb
- spec/models/sushi/report_list_spec.rb
some slight refactoring after reading the docs a bit more closely:
- #661 
- rename the "ReportInformation" class to "ReportList", since that is what the GET request is called
- rename #reports_array to #reports
- change the "Report ID" values to lowercase, per the docs: https://countermetrics.stoplight.io/docs/counter-sushi-api/af75bac10e789-report-list
- update all "Report_Name" values to match the name of their GET request in the docs
> 655-report-list-endpoint-v2

- app/forms/hyrax/cdl_form.rb
- spec/forms/hyrax/cdl_form_spec.rb
Ref
- #679
Reorder CdlForm terms so that the form fields for :contributing_library and :library_catalog_identifier are listed first after the "Additional fields" button
The `Contributing library` and `Library Catalog Identifier` form fields are listed at the bottom of the form
The `Contributing library` and `Library Catalog Identifier` form fields are listed towards the top of the form. Specifically, they are listed first after the "Additional fields" button. 
<details><summary>"After" screenshot</summary>
</details>
> i679 Reorder CDL form fields

- app/forms/hyrax/etd_form.rb
- app/forms/hyrax/generic_work_form.rb
- app/forms/hyrax/image_form.rb
Refs
- #683 
The terms added by #prepend were bubbling up to the parent class (Hyrax::Forms::WorkForm). Depending on the order things were called in, this was causing issues on other Form classes that didn't have a property matching the prepended term(s):
```
unknown attribute 'library_catalog_identifier' for Etd
```
Even though both `prepend` and `+=` are mutators, `+=` doesn't seem to have the same "bubble up" behavior that `prepend` does.
As stated above, this only happened when things were run in a specific order; if the Form class with the unique term was invoked before a Form class that didn't have the term, it would appear on both classes:
```ruby
Hyrax::CdlForm.terms.include?(:contributing_library)
=> true
Hyrax::EtdForm.terms.include?(:contributing_library)
=> true
reload!
=> …
```
> Remove #prepend from all Form classes (except CDL)

- app/controllers/api/sushi_controller.rb
- app/models/sushi.rb
- app/models/sushi/platform_report.rb
- app/models/sushi/platform_usage_report.rb
- app/models/sushi/report_list.rb
- spec/models/sushi/platform_usage_report_spec.rb
- spec/models/sushi/report_list_spec.rb
- spec/models/sushi_spec.rb
This commit contains two primary changes:
1. Favoring objects responding to `#as_json`
2. Date range boundaries for Sushi report dates
**`#as_json`**
In Rails, when an object responds to `#as_json`, that object can be directly passed to the `render json: object` directive, and Rails will "figure it out".
This refactor also adds a spec to the Sushi::PlatformUsageReport. Having a single spec will help us with further code refactoring as we discover common behavior.
**Date Range Boundaries**
In discussions with team members, the date range boundaries happen in month chunks.  I have taken time to write specs whose documentation (e.g. the strings after the `it` and `context` and `describe`) read as the intended behavior.
I have also added comments to explain the intention.  Please read these …
> ♻️ Refactor and Test Sushi Date Boundary Conditions

- Dockerfile
- docker-compose.yml
The primary change in Docker is moving from JDK 11 to 17 and improving the FITs xml config.
```
❯ git slog e9200061..f71b284f --no-merges
* e1c0510 — update fits xml Kirk Wang, (2022-12-01)
* 78eea74 — update jdk from 11 to 17 Kirk Wang, (2022-11-30)
* a404d11 — make cluster name a variable Rob Kaufman, (2022-11-19)
* d5745de — fix loki deploy Rob Kaufman, (2022-11-15)
```
Related to:
- https://github.com/scientist-softserv/palni-palci/issues/690
<details>
<summary>Commits since the reference point I'm bringing over from UTK</summary>
```
❯ git slog f71b284f.. --no-merges
* 99e6df9 — remove mimir, fix postgres Rob Kaufman, (2023-07-20) (origin/mimir_begon)
* 7e3d1c2 — add signoz to stack Rob Kaufman, (2023-06-21) (origin/signoz)
* abb6747 — build a new version of the LB with opentracing …
```
> 🐛 Use UTK Hyku build

- app/presenters/hyku/work_show_presenter.rb
- app/services/iiif_print/tenant_config.rb
- config/application.rb
- spec/presenters/hyku/work_show_presenter_spec.rb
- spec/presenters/hyrax/oer_presenter_spec.rb
- spec/services/iiif_print/tenant_config_spec.rb
There is a conflict between the `IiifPrint` and `Hyrax::IiifAv` gems; namely they both have strong opinions about how to sniff out if we should use the `iiif_viewer?`.  Compounding this, is that IiifPrint decorates `Hyrax::WorkShowPresenter` and Hyku extends `Hyrax::WorkShowPresenter` then includes
`Hyrax::IiifAv::DisplaysIiifAv`.
The end result is that the logic to determine if we should show pages split from the PDF is never called.  Yet, if we were to solely use IiifPrint we'd ignore rendering audio and vidoe in the iiif viewer.
So this commit peels that back so that we're using the logic (brought forward by IiifPrint) but ensuring our Hyku presenters are using that logic.
Why move the logic out of the Hyku instance and into a module?  Because that module contains the per-tenant antics …
> 🐛 Ensure consistent logic path for when iiif viewer

- app/controllers/api/sushi_controller.rb
- app/models/sushi/report_list.rb
- config/routes.rb
- spec/models/sushi/report_list_spec.rb
- spec/requests/api/sushi_spec.rb
This feature is not currently needed, so we're not going to worry about maintaining it.
Ref
- #694
- Can see a "Members List" report name in the report list (`/api/sushi/r51/reports`) 
- Can view the members report at `/api/sushi/r51/members` 
- Cannot see a "Members List" report name in the report list (`/api/sushi/r51/reports`) 
- Cannot view the members report at `/api/sushi/r51/members` 
<details>
<summary>No "Members List" report name</summary>
</details>
---
Co-authored-by: Alisha Evans <alishaevn2@gmail.com>
Co-authored-by: Lea Ann Bradford <ltrammer@gmail.com>
> i694 Remove member list report from the reports list

- config/features.rb
- spec/services/iiif_print/tenant_config_spec.rb
Refs #659 
Client would like default for using IIIF Print to be false
<details>
</details>
> Change default for use iiif_print to false per client request

- Gemfile
- Gemfile.lock
To leverage spring, you will need to:
- Start the containers (e.g. `sc up`)
- Run the specs using spring (e.g. `spring rspec path/to/my_spec.rb`)
Spring boots up a Rails server and re-uses that between invocations. This means that instead of spending about 1 minute booting the application to run a 1 second test, you can re-use that app (spending about 8 seconds or so connecting to it) then run that 1 second test.
But beware of spring, as it can create odd behavior in the application. As a matter of practice when you are done testing, run `spring stop` to terminate the spring booted applications.
In past years, some of the pernicious bugs in development were because folks had spring running.  However, for unit tests, having a quick feedback is critical so I believe this is worth the risk. …
> ☑️  Add spring to provide option for faster tests

- app/models/sushi.rb
- app/models/sushi/platform_report.rb
- spec/models/sushi/item_report_spec.rb
- spec/models/sushi/platform_report_spec.rb
- spec/support/helpers.rb
Adds a Granularity filter to the Platform Report
Granularity - documentation: https://cop5.projectcounter.org/en/5.1/03-specifications/03-counter-report-common-attributes-and-elements.html#report-filters-and-report-attributes
- #686 
- User could not filter by granularity
- Go to `/api/sushi/r51/reports/pr?begin_date=2023-05&end_date=2023-07&granularity=totals`
- Check that you see the total counts for each metric type as opposed to the counts separated by month. 
Video : https://share.getcloudapp.com/DOuKZRdW
<details>
<summary>JSON example</summary>
</details>
> 686 Granularity Filter

- app/presenters/concerns/hyrax/iiif_av/displays_content_decorator.rb
- spec/presenters/concerns/hyrax/iiif_av/displays_content_decorator_spec.rb
Prior to this commit, we had a private `#solr_document` method.  This resulted in an error in the `Hyrax::Ability` as follows:
```
NoMethodError
private method `solr_document' called for #<Hyrax::IiifAv::IiifFileSetPresenter:0x00007ff118124808>
Did you mean?  solr_document=
```
With this commit, I'm making public two methods that might cause issues being private.  (And adding a test verifying the interface)
Oh dear reviewer, were that I were able to duplicate the bug locally.  I tried toggling on and off the feature flag.  I also tried toggling the allow downloads.  But to no avail.  Alas, I cannot replicate but must instead rely on addressing the specific error.
Related to:
- https://github.com/scientist-softserv/palni-palci/issues/659
- …
> 🐛 Fix issue of calling private solr_document method

- app/assets/stylesheets/hyku.scss
references scientist-softserv/palni-palci#712
Hides the IIIF print feature flipper in the UI per customer request
IIIF Print feature flipper shows on feature page
iiif print feature flipper is hidden in the UI
<details>
</details>
> Hide feature flipper for IIIF print in the UI

- lib/tasks/move_banner_images.rake
Refs
- #674 
Adds two new rake tasks: 
- `hyku:copy_banner_images`
- Will non-destructively copy all Hyku banner images across all tenants from the old file location to the new, expected location 
- **Run this one first** 
- `hyku:delete_old_banner_images`
- Clean up task: will delete all banner images in the old location 
- **Run this one second _after_ confirming the presence of banner images across exiting tenants**
> i674 Rake tasks to move banner images to new expected file location

- app/controllers/api/sushi_controller.rb
- app/models/sushi.rb
- app/models/sushi/item_report.rb
- spec/models/sushi/item_report_spec.rb
- spec/requests/api/sushi_spec.rb
refactor the item report errors
instead of always throwing a 422 error for having no results, we will throw a 422 only if the parameter given is invalid. e.g., the item_id does not exist in the `Hyrax::CounterMetric` table.
if there are no results because of the date range given however, we will throw a 404 and inform the user of that.
- #688
> 688 refactor query validation

- app/models/sushi.rb
- app/models/sushi/platform_usage_report.rb
- spec/models/sushi/platform_usage_report_spec.rb
Adds the metric type filter to the platform usage report
- #687 
- users could not filter by metric type
<details>
<summary>JSON Structure when filtering by total_item_requests</summary>
</details>
> 687 Metric type filter for platform usage report

- app/views/hyrax/base/_representative_media.html.erb
Prior to this commit, the logic brough by IIIF Print was:
```html
<% if presenter.iiif_viewer? %>
<% if defined?(viewer) && viewer %>
<%= iiif_viewer_display presenter %>
<% else %>
<%= render media_display_partial(presenter.representative_presenter), file_set: presenter.representative_presenter %>
<% end %>
<% else %>
<% alt = block_for(name: 'default_work_image_text') || 'Default work thumbnail' %>
<%= image_tag default_work_image, class: "canonical-image", alt: alt %>
<% end %>
```
We would check if we should use the IIIF viewer.  And because we'd disabled it for the tenant, the answer was no.  The fallback was to then render a default thumbnail.
Related to:
- https://github.com/scientist-softserv/iiif_print/issues/276
- https://github.com/scientist-softserv/palni-palci/issues/715
- …
> 🐛 Render thumbnails when IIIF Print disabled

- app/services/generate_counter_metrics.rb
- lib/tasks/counter_metrics.rake
Sets up a rake task to get counter metric data on staging. 
- #699
- there was no real way to get counter metric data besides importing historical data.
> Rake task to get counter metric data on staging

- app/models/sushi.rb
- app/models/sushi/item_report.rb
- spec/models/sushi/item_report_spec.rb
create validations for the `access_method` query param.
if the `access_method` query param is passed in with at least one valid option, we return the valid option(s) to
be reflected in the `report filters` array.
if no valid options are passed through the param, we throw a `Sushi::InvalidParameterValue` error.
either way, the `access_method` that shows in the `item_report` is hard coded to say `Regular` because that's the only option we are allowing at this time. if that changes, the code in Sushi::ItemReport#report_items will need to be updated.
- #688
> 688 access method filter

- config/initializers/sentry.rb
Prior to this commit Sentry's default excluded
exceptions (e.g. `config.excluded_exceptions`) were as follows:
```ruby
["Mongoid::Errors::DocumentNotFound",
"Rack::QueryParser::InvalidParameterError",
"Rack::QueryParser::ParameterTypeError",
"Sinatra::NotFound",
"AbstractController::ActionNotFound",
"ActionController::BadRequest",
"ActionController::InvalidAuthenticityToken",
"ActionController::InvalidCrossOriginRequest",
"ActionController::MethodNotAllowed",
"ActionController::NotImplemented",
"ActionController::ParameterMissing",
"ActionController::RoutingError",
"ActionController::UnknownAction",
"ActionController::UnknownFormat",
"ActionDispatch::Http::MimeNegotiation::InvalidType",
"ActionController::UnknownHttpMethod",
"ActionDispatch::Http::Parameters::ParseError", …
```
> ⚙️ Reduce exceptions reported to Sentry

- app/models/cdl.rb
- app/models/etd.rb
- app/models/oer.rb
The OER, CDL, and ETD models are all abbreviations.  This commit adds a human readable name to this as well as a link to the wikidata.org node that describes the resource.
This work is in part my read through of the models in an effort to find the appropriate properties for `year of publication` and `author`; both fields required for the ongoing Sushi work.
Tangentially related to:
- https://github.com/scientist-softserv/palni-palci/issues/721
- https://github.com/scientist-softserv/palni-palci/issues/720
> 📚 Add description to models that are abbreviations

- config/initializers/bulkrax.rb
The view paths for the application are a bit unexpected.
- /gems/hyrax-doi-d494a50ef8ce/app/views
- /gems/bulkrax-5.3.0/app/views
- /app/samvera/hyrax-webapp/app/views
- /gems/iiif_print-eb320b1c454f/app/views
- /gems/hyrax-doi-d494a50ef8ce/app/views
- /gems/qa-5.10.0/app/views
- /gems/hyrax-ab3185d3069f/app/views
- /gems/browse-everything-1.2.0/app/views
- /gems/hydra-editor-5.0.5/app/views
- /gems/blacklight-gallery-0.12.0/app/views
- /gems/mailboxer-0.15.1/app/views
- /gems/flipflop-2.7.1/app/views
- /gems/devise_invitable-1.7.5/app/views
- /gems/devise-i18n-1.10.2/app/views
- /gems/devise-4.8.1/app/views
- /gems/bulkrax-5.3.0/app/views
- /gems/blacklight_range_limit-7.0.1/app/views
- /gems/blacklight_advanced_search-6.4.1/app/views
- /gems/blacklight-6.25.0/app/views
- …
> Ensure that Bulkrax sidebar navigation appears.

- config/application.rb
- spec/features/application_config_spec.rb
Prior to this commit, and with three engines (e.g. Bulkrax, Hyrax::DOI,
and AllinsonFlex), we had a situation in which the first view path may
not have been the application.  The consequence being that the view
lookup would potentially behave in unexpected ways.
Below is the commit message on the patches submitted for the three
engines.  The message further details the problem:
> Prior to this commit, the logic for finding the Hyrax in the view path
> was assuming a version number (e.g. `hyrax-2.`); however if the we
> pinned Hyrax to a branch/sha then we might have `hyrax-a`.  The result
> being that we pre-prended the view path into the application.  That
> created the conditions where the `view_paths` first element might not
> have been the application but instead a gem/engine.
>
> …
> 🐛 Ensure Hyku's view_path is first in list

- app/models/sushi/server_status.rb
- spec/models/sushi/server_status_spec.rb
Refs #653 
Client feedback is to remove the alerts section from the status report
An empty alert was part of the status report
The alert section is removed from the status report
<details>
</details>
> remove alerts from status report

- app/models/sushi.rb
- app/models/sushi/item_report.rb
- spec/models/sushi/item_report_spec.rb
- spec/models/sushi_spec.rb
- spec/support/helpers.rb
Before this commit, we were not handling the `:yop` query parameter.
With this commit, we're parsing the given `:yop` to build the date range
query over the `Hyrax::CounterMetric#year_of_publication` field.
Related to:
- https://github.com/scientist-softserv/palni-palci/issues/720
- https://github.com/scientist-softserv/palni-palci/issues/688
> 🎁 Adding year_of_publication filter to Sushi report

- app/models/sushi.rb
- app/models/sushi/item_report.rb
- spec/models/sushi/item_report_spec.rb
- spec/models/sushi_spec.rb
Prior to this commit, when given a YOP we were not providing that value
as part of the response document.
With this commit, when we're provided a YOP, we include that as part of
the "Report_Header > Report_Filters".
Related to:
- https://github.com/scientist-softserv/palni-palci/issues/720
- https://github.com/scientist-softserv/palni-palci/issues/687
> 🐛 Add YOP to Report_Header > Report_Filters when provided

- app/models/sushi.rb
- app/models/sushi/item_report.rb
- app/services/import_counter_metrics.rb
- spec/models/sushi_spec.rb
- spec/support/helpers.rb
Prior to this commit, we made the short-cut assumption that each work would have one author.
With this commit, we now serialize authors in the `author` field and then query accordingly.  The query is setup to be backwards compatible with already imported data.
Related to:
- https://github.com/scientist-softserv/palni-palci/issues/721
> 🎁 Add multiple author handling to Sushi report

- app/assets/stylesheets/hyrax.scss
- app/controllers/application_controller.rb
- app/controllers/catalog_controller.rb
- app/indexers/app_indexer.rb
In this PR we are indexing the pdf text onto the parent record, adding a highlight to the matching search results and displaying the snippet in the search catalog. An index will be required when we deploy to the various environments. 
Refs #772 
Search results were not displaying as a highlight on the search catalog page.
> :gift: Enable snippet highlighting for search

- app/helpers/pdf_js_helper.rb
- app/views/hyrax/base/_download_pdf.html.erb
- app/views/hyrax/base/show.html.erb
- public/pdf.js/viewer.html
This PR adds the download btn to the show page. It also hides the ability to download the PDF from within the PDF.js.
Refs #774
> :gift: I774 add download btn to show page

- app/indexers/app_indexer.rb
This commit will guard the work indexing with a Flipflop check so we don't get stuck at the AttachFilesToWorkJob.
Refs #772 
If an admin switched to UV which uses IIIF Print logic, the works never get completely created.
The works complete.
> 🐛 Account for IIIF Print logic

- app/views/themes/image_show/hyrax/base/show.html.erb
- app/views/themes/scholarly_show/hyrax/base/show.html.erb
- app/views/themes/scholarly_show/hyrax/oers/show.html.erb
Originally this was developed on only the default theme and the other themes looked weird.  This commit will fix that.
Refs #125
> 🐛 PDF.js looks better in other themes

- app/controllers/catalog_controller.rb
- app/helpers/blacklight/blacklight_helper_behavior.rb
- app/views/advanced/_advanced_search_fields.html.erb
Since #738 and #739 were so closely related, I thought it would have been easier to address them in one PR.
This commit reorders the advanced search fields to match the preferred priority order:
`Title`
`Creator`
`Date or Date Created`
`Keyword`
`License`
`Subject`
Ref:
- https://github.com/scientist-softserv/palni-palci/issues/738
---
This commit will only show the first six search fields in the advanced search form. The rest of the fields will be hidden behind an "Additional fields" button that mimics the Hyrax forms behavior.
Ref:
- https://github.com/scientist-softserv/palni-palci/issues/739
> 🧹 Reorder advanced search fields

- config/authorities/resource_types.yml
Text should also be included in the authority file for resource_types
Refs #741 
related to https://github.com/scientist-softserv/palni-palci/pull/785
The client kicked this back because Text should be included too, per [this document](https://docs.google.com/spreadsheets/d/1iIzTikHdXKo8u1_Re_CuE_LhnI0o-62WqYdKYGAt1BE/edit#gid=519636467). Text was not part of the original ticket. 
Text was not a resource type
Text is now a resource type and is in alphabetical order.
<details>
<summary>demo</summary>
edit form
show page
</details>
> :gift: i741 - add Text to resource types

- app/controllers/application_controller.rb
- app/helpers/iiif_print_helper.rb
Sometimes when you search for a phrase the results will throw an exception.  This commit will fix that by calling the IIIF Print version of the `#render_ocr_snippets` method.
Ref:
- https://github.com/scientist-softserv/palni-palci/issues/772
> 🐛 Fix double render error

- app/helpers/blacklight/advanced_search_helper.rb
- app/helpers/blacklight/blacklight_helper_behavior.rb
- app/views/advanced/_advanced_search_fields.html.erb
- app/views/advanced/_advanced_search_fields_qa.html.erb
- spec/helpers/blacklight/advanced_search_helper_spec.rb
On the advanced search page, the controlled vocab properties currently allows the user to input whatever they want. Instead, the user should have to select an option from a dropdown.
Refs #740 
controlled vocab fields were inputs. the user could type in whatever they want. 
the user must select an option provided by their local controlled vocab configuration.
<details>
<summary>DEMO</summary>
https://github.com/scientist-softserv/palni-palci/assets/10081604/feda32f1-b31b-49c1-a327-f58860d42f3e
</details>
> :gift: i740 -  local controlled vocabulary properties should display dropdown

- app/controllers/application_controller.rb
- app/controllers/devise_decorator.rb
- app/controllers/single_signon_controller.rb
- app/controllers/users/omniauth_callbacks_controller.rb
- app/models/work_authorization.rb
- app/views/devise/omniauth_callbacks/complete.html.erb
- app/views/hyrax/base/unauthorized.html.erb
- config/initializers/devise.rb
- lib/omni_auth/strategies/open_id_connect_decorator.rb
- spec/models/work_authorization_spec.rb
- spec/omni_auth/strategies/open_id_connect_decorator_spec.rb
58a5728d34193c6521258f1f6537a4bc701f315c
Prior to this commit, we had not wired in the logic for authorization to
controlled digital lending (CDL) assets.  With this change, we're adding
the logic for handling a user authenticating to access a work.
The logic flow is as follows:
An unauthenticated user goes to a CDL asset page.  They are neither
authorized nor authenticated, so we direct them to the new session
route.  There we capture we're the URL of the requested resource and
send them on their way to authenticate.
When we perform the handshake with OpenID, we provide (as scope and
client design decision) the URL of the CDL asset.  The OpenID provider
authenticates and returns to the OmniAuth callback.  We use the returned
scope to then grant authorization to the CDL asset (and revoke …
> 🎁 Add AuthN/AuthZ for CDL assets

- app/forms/hyrax/pdf_form_behavior.rb
- app/views/records/edit_fields/_default.html.erb
The `show_pdf_viewer` and `show_pdf_download_button` fields were showing up on the form so this commit will remove them.
> 🐛 Remove PDF.js related fields from form

- Gemfile
- Gemfile.lock
This commit updates Bulkrax to allow `Institution` to be an option for importers.
Refs #747 
The only options on the Bulkrax importer page for visibility were `Public` and `Private`.
The `Institution` option as been added.
> 🎁 Add `Institution` option for Bulkrax importers

- app/assets/stylesheets/hyku.scss
- app/views/hyrax/base/_download_pdf.html.erb
This commit will adjust the css to fix the download button so it would look the same on the cultural theme as it does on the other themes.
> 🐛 Adjust download button styling

- app/models/featured_collection_list.rb
- spec/models/featured_collection_list_spec.rb
This commit will add a default A-Z title sort to the featured collections section on the homepage.  If a featured collections list has been saved then it will no long sort by title but instead whatever the user set it to.
Refs #743 
By default, featured collections would be sorted by the last added.
By default, featured collections would be sorted by title.
https://github.com/scientist-softserv/palni-palci/assets/19597776/04bb3109-ec5e-4de4-9e6b-b60510bbb605
When the user saves a list, this functionality will stop working until the list has been cleared and new collections added.
> 🎁 Default A-Z title sort for featured collections

- app/controllers/concerns/hyrax/collections_controller_behavior_decorator.rb
This commit will add a sort_by for the subcollections and make them sort by title.
Ref:
- https://github.com/scientist-softserv/palni-palci/issues/744
> I744 sort subcollections a z

- app/views/splash/index.html.erb
The footer section had a typo.  Fixes issue on this ticket: https://github.com/scientist-softserv/palni-palci/issues/677
Refs #issuenumber https://github.com/scientist-softserv/palni-palci/issues/677
No more typo on word institute in the splash footer. 
<details>
</details>
> Update index.html.erb - Fix typo on Institute

- app/controllers/catalog_controller.rb
Remove date modified sort_by options from the catalog controller.
Issue:
- https://github.com/scientist-softserv/palni-palci/issues/745
Refs #745
> :gift: remove sort by date modified

- app/controllers/api/sushi_controller.rb
- app/models/sushi.rb
- app/models/sushi/error.rb
- app/models/sushi/item_report.rb
- app/models/sushi/report_list.rb
- spec/models/sushi/item_report_spec.rb
- spec/models/sushi/platform_report_spec.rb
- spec/models/sushi_spec.rb
- spec/requests/api/sushi_spec.rb
The [spec defines numerous exceptions][1].  This refactor moves towards
conforming to those specifications.
This change also builds on raising exceptions when data is not yet
ready.  To then guard against those exceptions, we need to either rescue
in the JSON document (which would be rather gross) or wrap the Sushi
methods with a guarding function.  I chose the latter.
See the inline comments for further discussion/documentation on these
changes.
Related to:
- https://github.com/scientist-softserv/palni-palci/issues/688
[1]: https://countermetrics.stoplight.io/docs/counter-sushi-api/sgmqulr0emsi6-exception
> Resolving sushi error handling

- lib/oai/provider/metadata_format/hyku_dublin_core.rb
- lib/oai/provider/model_decorator.rb
- spec/features/oai_pmh_spec.rb
Note that these ONLY show on the oai_hyku format, because the requested terms are not valid terms for oai_dc.
Refs:
#737   - Uses term "repository" to display the account cname 
#736  - Uses term "oai_id" to display the identifier
#733  - Uses term "thumbnail_url" to display the thumbnail
Adds 3 new terms to oai_hyku section of xml
<details>
<summary>OAI response</summary>
</details>
> Add data to OAI feed for format oai_hyku

- app/models/sushi.rb
- spec/models/sushi/platform_report_spec.rb
- spec/requests/api/sushi_spec.rb
- spec/support/helpers.rb
This commit introduces error handling for:
- filtering begin date that occurs before the earliest date of stored
statistics.
- filtering end date that occurs after the latest date of stored
statistics.
Related to:
- https://github.com/scientist-softserv/palni-palci/issues/688
- https://github.com/scientist-softserv/palni-palci/pull/804
- https://github.com/scientist-softserv/palni-palci/pull/764
- https://github.com/scientist-softserv/palni-palci/issues/792
Closes: #792
> 🎁 Add error handling for usage date range

- app/models/sushi/item_report.rb
- app/models/sushi/platform_report.rb
- app/models/sushi/platform_usage_report.rb
- spec/models/sushi/platform_report_spec.rb
Prior to this commit, the inner logic that built the array of data was
not using the begin and end date filter.
With this commit, those sub-queries are all limiting the queries to
those that are within the given date range.
Related to:
- https://github.com/scientist-softserv/palni-palci/issues/687
> 🐛 Ensure filter date range honored

- lib/oai/provider/metadata_format/hyku_dublin_core.rb
- lib/oai/provider/model_decorator.rb
Default to account cname if Application Name label is not filled.
Refs https://github.com/scientist-softserv/palni-palci/issues/810
Repository value in OAI shows account tenant url.
Repository value in OAI shows Application Name label if one is filled in, but otherwise defaults to account tenant url.
<details>
<summary>OAI getRecord</summary>
**Before:**
**After:**
</details>
> Use Application Name for repository

- app/views/hyrax/dashboard/sidebar/_repository_content.html.erb
The client reported double rendering of importer and exporter buttons. This is happening because we have the buttons rendering from a partial within PALS && bulkrax. This PR removes the code from the app since we're using the bulkrax gem and we know that bulkrax is enabled for this client. 
I am treating this as a hot fix. I realize I am not taking the time to understand WHY this is suddenly happening, since this code was introduced 4 years ago.
Issue:
- https://github.com/scientist-softserv/palni-palci/issues/767
Refs #767
> :bug: Remove bulkrax options from partials

- app/views/hyrax/file_sets/media_display/_pdf.html.erb
This commit will fix a bug where the Download PDF link was erroneously removed in a previous commit.  It was originally removed because it was rendering on the work show page but in doing so it was also removed from the file set show page.  We now bring it back with a conditional that only renders it on the file set show page.
Ref
- https://github.com/scientist-softserv/palni-palci/issues/814
- https://github.com/scientist-softserv/palni-palci/pull/788
> 🐛 Bring back missing download link on pdf

- app/helpers/application_helper.rb
- app/views/hyrax/file_sets/media_display/_pdf.html.erb
This commit will fix a bug relating to the ocr snippets.  Because we are using the the `markdown` helper, we need to make sure we are  not passing `nil` to it otherwise it'll break.  We are getting nil because we don't find any snippets and IIIF Print would return a nil so we don't display empty quotes on the search page.
> 🐛 Handle `nil` passing to Markdown

- app/models/sushi.rb
- spec/models/sushi_spec.rb
According to the Sushi spec, the [Item Report][1] does not account for multiple authors.
> Identifier of a specific author usage is being requested for. If
> omitted, all items on the platform with usage for the customer will be
> returned.
Later, for `yop` there is language about how to encode multiple values.
Which, I believe means that if we include a `|` in the author we should
return a 3060.  So I'll set about working on that.  (That does assume a
person does not have a `|` in their name).  Note, the data encoding
we're doing is to have pipe separation of multiple authors in the
database.  The record you're seeing has `|Summer|Winter|` for a
multi-author file.  And there's a direct match.
Related to:
- https://github.com/scientist-softserv/palni-palci/issues/721
[1]: …
> 🐛 Raise 3060 Sushi Exception if | provide for author field

- app/views/themes/scholarly_show/hyrax/base/show.html.erb
The description was not being rendered in the scholarly theme. This commit will bring that logic in.
ref #823 
Before:
After:
> 🐛 Render description in scholarly theme

- app/views/themes/reshare_show/hyrax/base/show.html.erb
Refs #601
Buttons linking back to Reshare appeared in ReShare show page theme
Buttons linnking back to ReShare on the ReShare show page theme are no longer there
<details>
</details>
> Remove button links on ReShare Theme

- app/models/sushi.rb
add the closing parens to the message given to the
`Sushi::Error::InvalidReportFilterValueError` exception.
- https://github.com/scientist-softserv/palni-palci/issues/721#issuecomment-1736156017
<details>
</details>
> 721-missing-parens

- app/models/sushi/platform_report.rb
- app/models/sushi/platform_usage_report.rb
update filter handling for the platform and platform usage reports
`Searches_Platform` is a valid metric_type filter according to
https://countermetrics.stoplight.io/docs/counter-sushi-api/3wikuuhv4hnbv-pr-report-filters and https://countermetrics.stoplight.io/docs/counter-sushi-api/xggfvq5by3gx0-pr-p1-report-filters.
- https://github.com/scientist-softserv/palni-palci/issues/686#issuecomment-1707261846
- https://github.com/scientist-softserv/palni-palci/issues/687#issuecomment-1736117022
we were always returning `Searches_Platform`, despite whether a `metric_type` filter was being used.
we only return `Searches_Platform` if the `metric_type` param includes it, or is not being passed at all.
<details>
<summary>platform report</summary>
**no `metric_type` param**
**with …
> searches_platform sushi filter

- config/locales/devise_invitable.de.yml
- config/locales/devise_invitable.en.yml
- config/locales/devise_invitable.es.yml
- config/locales/devise_invitable.fr.yml
- config/locales/devise_invitable.it.yml
- config/locales/devise_invitable.pt-BR.yml
- config/locales/devise_invitable.zh.yml
- config/locales/en.yml
Re scientist-softserv/palni-palci#637
Invite emails are consistently being sent to spam. There are several reasons this might be happening, but having an html tag in the text is a possible cause. This PR removes the `<br />` tag from the locale.
Refs #637 
`<br />` tag shows in user invite email
No html tag in user invite email
> Remove <br> tag from invite email locale

- app/models/sushi.rb
- app/models/sushi/error.rb
- app/models/sushi/item_report.rb
- app/models/sushi/platform_report.rb
- app/models/sushi/platform_usage_report.rb
- spec/models/sushi/item_report_spec.rb
- spec/models/sushi/platform_report_spec.rb
- spec/models/sushi/platform_usage_report_spec.rb
- spec/models/sushi_spec.rb
accounting for begin/end dates passed as `MM/YYYY`.
This is necessary because calling `to_date` on a string in `MM-YYYY` format will assume that `MM` is the day, and will set the current month as `MM` instead.
We are also still allowing for dates to use `MM-DD-YYYY` format.
```
params.fetch(:begin_date) => "06-2023"
params.fetch(:begin_date).to_date => Wed, 06 Sep 2023
```
- https://github.com/scientist-softserv/palni-palci/issues/687#issuecomment-1736117022
accounting for exceptions in the report header
exception 0 is a special case, as it represents info or debugging messages.
when the query is successful, despite the exception, the exception is
to be returned as part of the report header.
ref: https://countermetrics.stoplight.io/docs/counter-sushi-api/jmelferytrixm-exception-0
ref: …
> 687-platform-usage-updates

- app/models/solr_document.rb
re: scientist-softserv/palni-palci#832
Refs #832 
Bibliographic citation was not appearing on the work show page
Bibliographic citation appears on the work show page
> Bibliographic Citation field not displaying

- app/models/sushi.rb
- app/models/sushi/error.rb
update the messaging for begin and end date exceptions when given dates that are before or after metric availability dates.
add spaces in the error message for #given_value_does_not_match_allowed_values
> 792 update exception messaging

- app/helpers/pdf_js_helper.rb
- app/views/hyrax/base/_representative_media.html.erb
- app/views/hyrax/base/show.html.erb
- app/views/themes/cultural_show/hyrax/base/show.html.erb
- app/views/themes/cultural_show/hyrax/oers/show.html.erb
- app/views/themes/image_show/hyrax/base/show.html.erb
- app/views/themes/reshare_show/hyrax/base/show.html.erb
- app/views/themes/scholarly_show/hyrax/base/show.html.erb
- app/views/themes/scholarly_show/hyrax/oers/show.html.erb
This commit will fix the logic for PDF.js to work when the first file set presenter is not a PDF.  We first select all pdf file set presenters and then select the first one.
> 🐛 Fix PDF.js logic

- app/jobs/reindex_collections_job.rb
- app/jobs/reindex_works_job.rb
This commit will bring back a change to `ReindexWorksJob` and `ReindexCollectionsJob` because the rake task is calling them with an argument while the jobs' parameters were removed.
Ref:
- https://github.com/scientist-softserv/palni-palci/commit/4285d0f4e2bd758562979730b29a1fa3b7a253e2
> 🐛 Fix the rake task's reindex jobs

- app/helpers/pdf_js_helper.rb
- app/views/hyrax/base/_representative_media.html.erb
- app/views/hyrax/base/show.html.erb
- app/views/themes/cultural_show/hyrax/base/show.html.erb
- app/views/themes/cultural_show/hyrax/oers/show.html.erb
- app/views/themes/image_show/hyrax/base/show.html.erb
- app/views/themes/reshare_show/hyrax/base/show.html.erb
- app/views/themes/scholarly_show/hyrax/base/show.html.erb
- app/views/themes/scholarly_show/hyrax/oers/show.html.erb
Currently, the file manager isn't selecting between PDFs for display in the viewer.  If there are multiple PDFs, changing the representative media/thumbnail doesn't affect which one displays in the viewer.  This commit will add the ability for the user to change which PDF is being displayed through the file manager.
Ref:
- https://github.com/scientist-softserv/palni-palci/issues/839
https://github.com/scientist-softserv/palni-palci/assets/19597776/a56bb856-de66-4e17-bafb-ef2d0ae632a1
> 🎁 PDF file sets now selectable in file manager

- app/models/account.rb
- app/models/concerns/account_settings.rb
- app/views/admin/accounts/edit.html.erb
- spec/models/concerns/account_settings_spec.rb
This commit will hide certain settings from non-superadmins on the Account settings dashboard page as prescribed by the client.
Ref:
- https://github.com/scientist-softserv/palni-palci/issues/841
<details>
<summary>As superadmin</summary>
</details>
<details>
<summary>As non-superadmin</summary>
</details>
> 🎁 Limit settings to superadmins

- app/presenters/concerns/hyrax/iiif_av/displays_content_decorator.rb
This commit will set the IIIF manifest URI for videos to be the Hyrax download video.  This is a temporary fix until we can get the [video processing speeds faster](https://github.com/scientist-softserv/palni-palci/issues/852).  It won't make a difference if the video that was ingested was already processed, however, this workaround falls apart if the uploaded video is a raw video file where the size could be enormous.  That is not ideal for streaming.
Ref:
- https://github.com/scientist-softserv/palni-palci/issues/853
Related: 
- https://github.com/scientist-softserv/palni-palci/issues/852
> 🩹 Temporary fix for video processing

- app/controllers/hyku/invitations_controller.rb
- spec/controllers/hyku/invitations_controller_spec.rb
Refs 
- #813 
Fixes a bug where users who were invited with no roles would not show up in the users list at all
When inviting an existing User account to a new tenant with no roles via the form in Dashboard > Manage Users (`/admin/users`), the user is not added to the tenant. 
When inviting an existing User account to a new tenant with no roles via the form in Dashboard > Manage Users (`/admin/users`), the user is added to the tenant. 
<details>
<summary>With changes</summary>
https://github.com/scientist-softserv/palni-palci/assets/32469930/784e2b58-79d6-4274-9dfb-ecb1f9b5bb10
</details>
> i813 Add invited users to the registered group

- .env
- app/controllers/admin/users_controller.rb
- app/views/hyrax/admin/users/index.html.erb
- config/locales/en.yml
- config/routes.rb
- ops/production-deploy.tmpl.yaml
- ops/staging-deploy.tmpl.yaml
- spec/controllers/admin/users_controller_spec.rb
This commit will allow superadmins to activate users from the dashboard. The default password for an activated user is set to `password`.  The activate button shows up for users who have permissions to destroy users.  The assumption is that superadmins will be the only ones with this permission.
Ref:
- https://github.com/scientist-softserv/palni-palci/issues/446
https://github.com/scientist-softserv/palni-palci/assets/19597776/8e797ee6-ff5e-421f-b29f-9d4ca61e8d36
The default password `password` is configurable through env variables.
> 🎁 Superadmins can activate users

- app/controllers/concerns/hyrax/works_controller_behavior.rb
- app/controllers/hyrax/admin/workflows_controller_decorator.rb
- app/controllers/hyrax/workflow_actions_controller_decorator.rb
This commit will add a redirect back to the review page after a user performs a workflow action from the work show page.  This will only occur if the user came from the review page.
Ref:
- https://github.com/scientist-softserv/palni-palci/issues/443
https://github.com/scientist-softserv/palni-palci/assets/19597776/3fc42b98-d6fd-443e-a860-3e50894152fd
> 🎁 Add redirect back to review page

- app/views/hyrax/admin/appearances/_banner_image_form.html.erb
- spec/views/hyrax/admin/appearances/show.html.erb_spec.rb
Failures from main:
1) hyrax/admin/appearances/show renders the edit site form
Failure/Error: assert_select "input#admin_appearance_banner_image[name=?]", "admin_appearance[banner_image]"
Minitest::Assertion:
Expected at least 1 element matching "input#admin_appearance_banner_image[name=\"admin_appearance[banner_image]\"]", found 0.
Expected 0 to be >= 1.
While investigating the flaky pipeline I noticed this spec was consistently failing. it also would fail locally. It appears to be the only valid failing spec. 
Refs #
- https://github.com/scientist-softserv/palni-palci/issues/860
> Fix for a valid failing spec

- app/views/hyrax/admin/appearances/_banner_image_form.html.erb
We updated the reference to an element in a previous commit and forgot to do it in all the necessary places. Because of this, the banner image crop feature stopped working in staging and failed QA
> 🧹 Fix cropper tool. It wasn't loading.

- .env
- config/initializers/hyrax.rb
- config/locales/simple_form.de.yml
- config/locales/simple_form.es.yml
- config/locales/simple_form.fr.yml
- config/locales/simple_form.it.yml
- config/locales/simple_form.pt-BR.yml
- config/locales/simple_form.zh.yml
- docker-compose.yml
The account setting's descriptions for contact_email and contact_email_to are confusing. This commit adds clarity to these configuration options. c/o Palni-Palci
TODO: 
- run translations
- Update superadmin logic. contact_email and contact_email_to should be viewable to non super admins too. 
ref: https://github.com/scientist-softserv/palni-palci/issues/841#issuecomment-1765451579
> 🧹 update description of contact_email and contact_to

- app/models/account.rb
- app/models/concerns/account_settings.rb
- spec/models/concerns/account_settings_spec.rb
This PR makes changes based on the client's clarifications: non super admins should have access to contact_email_to 
Issue:
- https://github.com/scientist-softserv/palni-palci/issues/841
<details> <summary> screenshot (non superadmin user) </summary>
</details>
<details> <summary> screenshot (superadmin user) </summary>
</details>
<details> <summary> screenshot (non superadmin user) </summary>
</details>
<details> <summary> screenshot (superadmin user) </summary>
</details>
> 🧹 contact_email_to should be exposed to non-superadmins

- app/controllers/admin/accounts_controller.rb
We noticed in staging that we weren't able to save the form when filling out the contact to account field. This is because it was considered an unpermitted param.
related: https://github.com/scientist-softserv/palni-palci/issues/841
> 🧹 Add contact_email_to to permitted params

- app/controllers/hyrax/my/works_controller_decorator.rb
- app/helpers/blacklight/configuration_helper_behavior_decorator.rb
- app/indexers/app_indexer.rb
- app/indexers/collection_indexer.rb
- app/services/hyrax/search_service_decorator.rb
- app/views/hyrax/my/_search_header.html.erb
- spec/controllers/hyrax/my/works_controller_spec.rb
[🎁 Add sort on dashboard works](https://github.com/scientist-softserv/palni-palci/commit/3afa0dd01ed4f3acf252da95cd48e7aed070c2d8) 
This commit will add the ability to sort on the dashboard works pages,
to include dashboard works and my works.
[🎁 Add ability to sort dashboard collections](https://github.com/scientist-softserv/palni-palci/commit/03efb9038a43a694fc8f8e06c96e842b4a5ec8f7) 
This commit will add the ability to sort collections on the dashboard.
The collections work differently than the works so we have to make sure
the sort field is added to the search builder.  Because when you click
into a collection can view the works attached to the collection, we have
to approach it differently because otherwise the sort fields from the
dashboard index page will also be applied to the …
> I748 sort works and collections on dashboard

- app/presenters/hyku/work_show_presenter.rb
- app/views/hyrax/base/_relationships.html.erb
- app/views/hyrax/base/_relationships_parent_works_rows.html.erb
- app/views/themes/cultural_show/hyrax/base/_relationships.html.erb
- spec/presenters/hyku/work_show_presenter_spec.rb
This is rework to address user abilities regarding the parent linked in a child work. It considers what should happen when a user is logged out and in. When logged it, it considers the user's abilities and the visibility type of the parent work.
Issue:
- https://github.com/scientist-softserv/palni-palci/issues/840
We misinterpreted the client's request. When logged out, the user could not see the parent link unless it also had a public collection 🙃 
I created a parent work of all visibility types (public, private, institution and embargo)
<details> <summary> works only </summary> 
</details> 
<details> <summary> with collections </summary>
</details>
<details> <summary> works only </summary> 
</details> 
<details> <summary> with collections </summary>
</details>
<details> <summary> works …
> 🧹 rework: A user should see the parent work link if they can

- app/models/ability.rb
- spec/features/create_work_spec.rb
This commit will add back the ability for everyone to be able to create a work.  This is one of the conditionals that need to be met for a user to deposit a work to an admin set.  The other is already being met, which is that the user has to have either a depositor role for that specific admin set or in a group that has a depositor role for that specific admin set.
Ref:
- https://github.com/scientist-softserv/palni-palci/issues/864
Prior to this commit, even if a user was granted the role of depositor to an admin set, they could not add a work.  If they were added in a group that had the depositor role, they still were not able to create a work.
Now, users who have the depositor role or in a group with the depositor role can deposit to admin sets. …
> 🐛 Fix user despositing to specific admin sets

- app/views/themes/institutional_repository/hyrax/homepage/_resource_type_stats.html.erb
This commit will fix the resource type link when it was less than 6 items.
> 🐛 Fix link on the resource type icon

- config/locales/simple_form.de.yml
- config/locales/simple_form.en.yml
- config/locales/simple_form.es.yml
- config/locales/simple_form.fr.yml
- config/locales/simple_form.it.yml
- config/locales/simple_form.pt-BR.yml
- config/locales/simple_form.zh.yml
This commit will fix the text of the contact_email and contact_email_to because they were swapped.
Corrected hint text:
This PR was branched off of the commit that was deployed to production on 19 OCT 23.
> 🐛 Switch contact_email and contact_email_to text

- app/views/hyrax/oers/show.html.erb
This commit will adjust the OER show page so it will properly show PDFs
> 🐛 Fix OER display of PDFs

- app/models/ability.rb
- app/models/concerns/hyrax/ability/work_ability.rb
Even though a user could not see the Add New Work or Collection button, they were still able to navigate to it via the routes.  This commit will rework the ability logic for depositor so that won't happen.
Ref:
- https://github.com/scientist-softserv/palni-palci/issues/864
> 🐛 Rework ability logic for depositor

- app/models/concerns/hyrax/ability/work_ability.rb
The client reported 500 errors in production. Locally, it displayed as a 404 because no users were found in the solr query it performed. We are overriding the method to rescue the case for nil ids.
ref: https://assaydepot.slack.com/archives/C0313NKC08L/p1698080533392449
Navigating to https://hykucommons.org/proprietor/users?locale=en and https://hykucommons.org/proprietor/accounts?locale=en resulted  in 500 errors
A user can successfully navigate to https://hykucommons.org/proprietor/users?locale=en and https://hykucommons.org/proprietor/accounts?locale=en without error.
> :fire: Hotfix - allow for ids to be empty in #admin_set_with_deposit?

- app/models/sushi/platform_report.rb
- spec/models/sushi/platform_report_spec.rb
Prior to this commit, when you provided an explicit
`metric_type=total_item_requests` you would get back the various data
types that had been seeded in the database.
When you'd provide the `metric_type=searches_platform` you would see the
DataType for the `Platform` (and not the Article nor Book data types).
When you'd provide ``metric_type=searches_platform|total_item_requests`
you would only get the `Platform` data type.
The expected behavior is you would get the `Article`, `Book`, and
`Platform` data types.
This commit remedies that behavior.  Note, dear reader, that the test
case only has `article` in the given date range.
See the Sushi Docs:
- https://countermetrics.stoplight.io/docs/counter-sushi-api/e98e9f5cab5ed-pr-platform-report
<details>
<summary>Copied text from …
> 🐛 Handle "or" behavior for specified metric types

- app/models/sushi/platform_report.rb
- spec/models/sushi/platform_report_spec.rb
Prior to this commit, if the query parameters included only non-platform data_type (e.g. article) then we would continue to show the platform data type node.
With this commit, we skip showing that element if we have been provided explicit data_type(s) and none of them are Platform.
Related to:
- https://github.com/scientist-softserv/palni-palci/issues/686#issuecomment-1785326034
> 🐛 Omit DataType=Platform when provided DataType does not include Platform

- app/views/hyrax/oers/show.html.erb
This commit will render the show_actions partial on the OER show page.
Ref:
- https://github.com/scientist-softserv/palni-palci/issues/888
> 🐛 Render show_actions on OER show

- ops/production-deploy.tmpl.yaml
ReindexCollectionsJobs are taking hours to complete
"Slow Sidekiq? 
If sidekiq is performing at an extremely slow pace (several hours to complete + seems to be stuck on CreateDerivativesJob ie: hyku project), consider adding the following env variable to the project's rancher cluster.
OMP_THREAD_LIMIT: 1"
ref: https://playbook-staging.notch8.com/en/dev/workers/sidekiq/sidekiq-debugging-tips
> 🐛 sidekiq is so slow

- app/controllers/hyrax/homepage_controller.rb
- app/views/themes/institutional_repository/hyrax/homepage/all_collections.html.erb
Fixing the app to use the graph indexer means that the query for top level collections will not work. It relied on an index field, `nesting_collection__deepest_nested_depth_isi` which was added by the nesting indexer. With the use of the graph indexer, this term no longer exists. 
This is a minor issue, as it ONLY affects the `all_collections` route for the homepage when using the `institutional_repository` theme, and this route is not linked anywhere. Without this change, the list of collections on this path would have been empty once collections are reindexed, as the queried term would no longer exist.
A simpler solution is to identify a top level collection as one which is not a member of any other collection. Along with this change, come code duplication is also being cleaned up.
Refs …
> 🐛 Fix top level collections

- config/features.rb
spltting has been corrected to splitting in the feature flipper description for :default_pdf_viewer.
Refs
- https://assaydepot.slack.com/archives/C031E2NF43T/p1701706582689099
> 🧹 Correct spltting typo

- Gemfile
- Gemfile.lock
The maintainers yanked 0.3.2 version; so we're falling back to 0.3.1.
Related to:
- https://github.com/dryruby/json-canonicalization/issues/2
> 🧹 Pin to json-canonicalization 0.3.1

- config/initializers/hyrax.rb
In this commit we are setting nested_relationship_reindexer in the Hyrax initializer to ensure the use of the nested indexer.
This stemmed from us noticing that adventist wasn't fully using the nested indexer when processing jobs. This should speed up reindexing.
> 🧹 Set nested_relationship_reindexer in Hyrax initializer

- RepoREADME.md
- app/assets/stylesheets/viewer.scss
- app/forms/hyrax/generic_work_form.rb
- app/models/generic_work.rb
- app/models/solr_document.rb
- app/presenters/hyku/work_show_presenter.rb
- app/views/hyrax/base/_form.html.erb
- app/views/hyrax/base/_video_embed_viewer.html.erb
- app/views/hyrax/base/show.html.erb
- app/views/layouts/hyrax/dashboard.html.erb
- config/initializers/bulkrax.rb
- config/locales/hyrax.en.yml
This commit allows videos to be embedded into a Generic Work. When the value is present, an embedded video should display.
related:
- https://github.com/scientist-softserv/atla-hyku/pull/34/files
Issue:
This PR is already large. I may create sub task for the tickets in attempts to keep this epic of work small. This PR only handles embedding the video for Generic Works, base theme, and in English only.
This feature previously did not exist.
A user can create a Generic Work and embed a video. If the value exists, the embedded video will display in the iframe of the show page and the user is able to play it. 
When there is an error on the form (ie: an invalid embed link), messages appear to say so:
> 🎁  Add video embed to Generic Work

- config/locales/hyrax.de.yml
- config/locales/hyrax.es.yml
- config/locales/hyrax.fr.yml
- config/locales/hyrax.it.yml
- config/locales/hyrax.pt-BR.yml
- config/locales/hyrax.zh.yml
In this PR, hyrax.en.yml gets translated to the various locales for the recently added video_embed help text.
Refs 
Switching from English to any other language would no longer display the help text for the video embed field: 
Switching from English to other languages displays the translated help text:
> 🎁 Video Embed Epic: Run translations

- config/tinymce.yml
Updates the Tinymce options to include font selection, font size, and font color options.
Addresses a rubocop violation.
Refs: https://github.com/scientist-softserv/palni-palci/issues/843
<details>
</details>
> 🎁 Add fonts & colors in content blocks

- app/forms/hyrax/oer_form.rb
- app/forms/video_embed_form_behavior.rb
- app/models/concerns/video_embed_behavior.rb
- app/models/oer.rb
- app/views/themes/cultural_show/hyrax/base/show.html.erb
- app/views/themes/scholarly_show/hyrax/base/show.html.erb
- config/locales/de.yml
- config/locales/en.yml
- config/locales/es.yml
- config/locales/fr.yml
- config/locales/it.yml
- config/locales/pt-BR.yml
- config/locales/zh.yml
This PR manually adds video embed to oer model, form files, and show partial.
It also includes translations. 
Issue:
Vimeo example: https://player.vimeo.com/video/467264493?h=b089de0eab
> 🎁 Add video embed to OER Work Type

- app/presenters/concerns/hyrax/iiif_av/displays_content_decorator.rb
This commit will use `audio/mpeg` as the mime type for mp3 resources in the IIIF manifest instead of relying on the characterized mime type of the original file.  This is a problem when our file is a wav file and it gets characterized as `audio/x-wave` which doesn't work with Universal Viewer.  Instead, since we are serving up the mp3 derivative in the manifest, we should use `audio/mpeg` as the mime type.  We also remove the ogg format because it is not being used and having that hard coded as `audio/mpeg` as well feels incorrect.  This however doesn't solve the bigger problem of the File Set not gettig the original file in the first place but that is a separate issue and would need some investigation.
Ref:
- https://github.com/scientist-softserv/palni-palci/issues/887 …
> 🐛 Fix audio mime type for IIIF manifest

- lib/tasks/remove_dickinson_placeholder_thumbnails.rake
This commit will add a rake task to remove placeholder file sets from the Dickinson tenant.  To test, set an environment variable with whatever cname you want to use and run the task.  For example:
```sh
REMOVE_PLACEHOLDER_FILE_SETS_FROM="dev.hyku.test" rake hyku:remove_placeholder_file_sets
```
Ref:
- https://github.com/scientist-softserv/palni-palci/issues/912
This should only be run once and future file sets of the placeholder pdf should not appear.
Tested locally and it worked for me.
> 🧹 Add task to remove placeholder file sets

- spec/features/admin_dashboard_spec.rb
- spec/features/feature_flag_spec.rb
These specs consistently fail the pipeline, and we typically ignore them. When a valid bug was introduced we could've easily missed it. This commit skips these specs in favor of a green pipeline. A ticket has been created to document and investigate it at a later time.
Issue:
- https://github.com/scientist-softserv/palni-palci/issues/933
> ✅ Skip specs consistently failing on CI pipeline

- .env
- README.md
- app/models/concerns/account_settings.rb
- app/views/shared/_ga4.html.erb
- config/locales/simple_form.de.yml
- config/locales/simple_form.en.yml
- config/locales/simple_form.es.yml
- config/locales/simple_form.fr.yml
- config/locales/simple_form.it.yml
- config/locales/simple_form.pt-BR.yml
- config/locales/simple_form.zh.yml
- config/settings.yml
06aa95b771ef7c90a420c49b621a2ac465812b8c
This commit will revert the previous Google Analytics work and modify it
to use the new Google Analytics 4 (GA4) tracking code.
Ref:
- https://github.com/scientist-softserv/palni-palci/pull/479
323169275108288de70ca626a575890187036c06
This commit will overwrite Hyrax's ga4 partial to handle Hyku's
multitenancy.
Ref:
- https://github.com/scientist-softserv/palni-palci/issues/910
Google Analytics was using the deprecated Universal Analytics from Google Analytics.
Now we are using Google Analytics 4.
<details>
<summary>Proprietor</summary>
</details>
<details>
<summary>Tenant same as Proprietor</summary>
</details>
<details>
<summary>Tenant Google Analytics ID not set</summary>
</details>
<details>
<summary>Tenant different than Proprietor</summary> …
> I910 google analytics

- app/views/shared/_ga4.html.erb
The `#current_account` method returns a tenant instance when on the proprietor page (not in a tenant subdomain). This then looks for a `HYKU_GOOGLE_ANALYTICS_ID` instead of the `GOOGLE_ANALYTICS_ID` env variable.  We want to only use the `GOOGLE_ANALYTICS_ID`.
Ref:
- https://github.com/scientist-softserv/palni-palci/issues/910
> 🧹 Tighten tenant GA ID logic

- app/models/site.rb
⚠️ Deploying this requires a reindex of works and collections! ⚠️
The client set an institution label for a tenant as "PVCC" and was surprised to see the display labeled as "PVCC Research Repository". Originally the client asked for feature parity with BL, so this was implemented they way they do it.
ref: https://assaydepot.slack.com/archives/C0313NKC08L/p1702649455056029?thread_ts=1702588480.326439&cid=C0313NKC08L
Issue:
- https://github.com/scientist-softserv/palni-palci/issues/915
> 🧹 Remove "Research Repository" from institution label

- app/presenters/hyrax/collection_presenter_decorator.rb
- spec/features/admin_dashboard_spec.rb
- spec/presenters/hyrax/collection_presenter_decorator_spec.rb
*Background:* A search_only tenant renders SOLR documents that had home
tenants different than the search_only tenant.  Part of that rendering
includes the underlying Work's collection type.  The SOLR document
stores the `Hyrax::CollectionType`'s ID.
The search_only tenant might have the same ID for
`Hyrax::CollectionType` but it is not the same thing.  Further, the home
tenant might have an ID that is not in the search_only tenant, which
results in an `ActiveRecord::RecordNotFound` error.
Prior to this commit, we always attempted to render the badge.
With this commit, we add some guarding logic to avoid rendering the
badge when we're likely not rendering within the SOLR documents home
tenant.
Related to:
- https://github.com/scientist-softserv/palni-palci/issues/951
- …
> 🐛 Skip rendering badges on search_only tenants

- .rubocop.yml
- app/views/splash/_search_form.html.erb
- app/views/splash/index.html.erb
- config/application.rb
- config/locales/en.yml
- ops/demo-deploy.tmpl.yaml
- ops/production-deploy.tmpl.yaml
- spec/config/application_spec.rb
This feature introduces a search on the proprietor's home page (e.g. the
root host of the Hyku instance).
That form will then submit a search against the configured host for
cross-tenant searching.
In the case of "commonsarchive.org", that will be
"//search.commonsarchive.org/catalog" (as demonstrated in the hard-coded value).
Related to:
- https://github.com/scientist-softserv/palni-palci/issues/947
> 🎁 Add search form to splash page

- app/assets/stylesheets/single_signon.scss
- app/jobs/create_group_and_add_members_job.rb
- app/jobs/destroy_cdl_group_job.rb
- app/jobs/destroy_split_pages_job.rb
- app/jobs/iiif_print/create_relationships_job_decorator.rb
- app/models/cdl.rb
- app/models/sushi.rb
- app/models/work_authorization.rb
- app/views/devise/omniauth_callbacks/complete.html.erb
- app/views/single_signon/index.html.erb
- lib/tasks/create_group_and_add_members.rake
- spec/jobs/create_group_and_add_members_job_spec.rb
- spec/jobs/destroy_cdl_group_job_spec.rb
- spec/jobs/destroy_split_pages_job_spec.rb
- spec/jobs/iiif_print/create_relationships_job_decorator_spec.rb
- spec/models/work_authorization_spec.rb
- spec/tasks/create_group_and_add_members_spec.rb
The clients requested a loading screen that covers the entire page so users can't click on anything while the redirect is happening.
https://github.com/scientist-softserv/palni-palci/assets/19597776/9efc588f-eaff-41f1-a3c6-0380da8a9514
> 🎁 Add loading splash screen and speed up redirect

- app/jobs/iiif_print/create_relationships_job_decorator.rb
- spec/jobs/iiif_print/create_relationships_job_decorator_spec.rb
Originally the `CreateGroupAndAddMembersJob` was keyed off the `Cdl` model but after the refactor, that was no longer the case.  This fix will add a conditinal for the `CreateGroupAndAddMembersJob` to only run if the resource is a `Cdl`.
> 🐛 Call `CreateGroupAndAddMembersJob` only for CDL

- lib/tasks/tenants.rake
When task reaches a search-only tenant, it hangs for awhile before exiting with a `Killed` error
> Skip search_only tenants when calculating usage

- app/jobs/create_derivatives_job_decorator.rb
- app/jobs/create_large_derivatives_job.rb
- config/sidekiq.yml
- spec/jobs/create_derivatives_job_spec.rb
- spec/jobs/create_large_derivatives_job_spec.rb
Refs
- #852 
@orangewolf and I determined that the slowness identified in #852 is due to insufficient CPU resources; `ffmpeg` commands run on large files were being throttled and thus running extremely slowly. 
To solve this, we decided that when an audio or video derivative job is triggered, we should put in into a separate Sidekiq queue (i.e. `:resource_intensive`). We'll have the default worker(s) run all queues other than `:resource_intensive`. We'll also have a new, separate worker that runs all the other queues plus the `:resource_intensive` queue. The new worker will have 4x the CPU resources that the default workers have, but only 1 thread.
This effectively creates a powerful "slow lane". `:resource_intensive` jobs will slow down the separate worker while they're running, but they …
> i852 Improve slow video processing speeds

- app/controllers/users/omniauth_callbacks_controller.rb
- app/models/user.rb
SSO is failing for Pitt. Logs show that this is because the user already has an email in the system and therefor SSO can not create a new user with that email.
Pitt SSO log in fails
Pitt SSO log in succeeds
> show errors for sso failure, handle sso from users with an existing email address

- app/controllers/users/omniauth_callbacks_controller.rb
- app/views/hyrax/admin/appearances/_banner_image_form.html.erb
When cropper.js intercepts an updated banner image file and crops it, the original filename gets changed to cropped.jpg which gets saved to disk.  When another tenant crops their banner image, it also gets saved as cropped.jpg and overwrites the previous tenant's banner image.  In this commit, we prepend the tenant name so it would look something like `shared-cropped.jpg` and `uindy-cropped.jpg` instead and avoids the files from being overwritten.
Ref:
- https://github.com/scientist-softserv/palni-palci/issues/948
- https://github.com/scientist-softserv/palni-palci/issues/746
Banner images were being overwritten.
Banner images have unique names based off the tenant so overwriting the name shouldn't be possible.
UIndy tenant has the banner image with filename being `cropped.jpg`
Search …
> 🐛 Fix cropped banner images being overwritten

- app/parsers/bulkrax/csv_parser_decorator.rb
- spec/parsers/bulkrax/csv_parser_decorator_spec.rb
Prior to this commit we were blanket checking CSV recores for the presence of title and resource_type.  The problem with this approach was that all models were being checked for these fields while not all models required these fields, such as the Collection and FileSet models.
In this commit we leverage the exisiting `Bulkrax::CsvParserDecorator` to check each model's actual required fields according to their respective forms (minus the FileSet which do not have required fields) and add logic to check any custom parser mappings according to the bulkrax initializer and also any numbered fields.  The error message was also changed to indicate which model was missing what required field(s).
Ref:
- https://github.com/scientist-softserv/palni-palci/issues/436
<details>
<summary>Oer</summary> …
> 🎁 Add a more nauced approach to required elements

- app/indexers/app_indexer.rb
- spec/indexers/app_indexer_spec.rb
Prior to this commit when the date_created property was indexed, only the year was indexed.  If the input was something like "2024-01-01" then `date_ssi` would only be "2024".  This commit will index YYYY-MM-DD, YYYY-MM, and YYYY if given.  Anything other than those three formats will be indexed as is and won't work correctly with sorting or range queries.
Ref:
- https://github.com/scientist-softserv/palni-palci/issues/973
YYYY-MM-DD, YYYY-MM, and YYYY dates were indexed just as YYYY.
YYYY-MM-DD, YYYY-MM, and YYYY dates are indexes as YYYY-MM-DD, YYYY-MM, and YYYY respectively.
> 🐛 Fix date indexing to return more than YYYY

- app/views/themes/scholarly_show/hyrax/base/show.html.erb
Refs https://github.com/scientist-softserv/palni-palci/issues/958
A work showing the PDF.js viewer did not show the description when using Scholarly Show Page theme.
Description shows for all themes and viewer options.
<details>
</details>
> Add description to show page

- app/views/splash/index.html.erb
Ref:
- https://github.com/scientist-softserv/palni-palci/issues/830
The proprietor splash page did not have the Hyku version, license, or private policy link.
Now it does.
> 🎁 Add Hyku version and license to proprietor page

- Gemfile.lock
Ref:
- https://github.com/scientist-softserv/palni-palci/issues/711
See:
- https://github.com/samvera/hyrax/commit/285982850cd95f4e322948e8f7d43388a4a37f01
We were getting uninitialized constant errors when going to the /works/:id/stats route.
We don't get errors anymore but the stats still doesn't work, waiting for GA to be functional for that to start working.
> 🐛 Update Hyrax to avoid GA errors

- app/models/concerns/order_metadata_values.rb
Ordering based_near causes several issues:
- adding a work to a collection fails
- adding a work outside of the actor stack turned the attribute into a string.
Refs:
- https://github.com/scientist-softserv/palni-palci/issues/892
- https://github.com/scientist-softserv/palni-palci/issues/964
Adding a work with a location value to a collection fails.
Adding a work with a location value to a collection succeeds
The location term is not ordered.
> Do not order location attribute

- config/initializers/bulkrax.rb
Ref:
- https://github.com/scientist-softserv/palni-palci/issues/990
The `admin_note` property was not mapped to Bulkrax
Now it is.
> 🎁 Add admin_note to bulkrax.rb

- app/models/concerns/bulkrax/has_matchers_decorator.rb
- spec/models/concerns/bulkrax/has_matchers_decorator_spec.rb
This commit will fix a bug where if the csv has a `location` header but no value.
> 🐛 Account for when result is not a string

- app/views/hyrax/admin/appearances/_banner_image_form.html.erb
The banner crop javascript was doing a `e.preventDefault();` which then allowed the form being submitted without the alt text which is a required field.  This commit will add a check to see if all the required fields are filled in and if not then the function should not execute and therefore not preventDefault.
Ref:
- https://github.com/scientist-softserv/palni-palci/issues/948
https://github.com/scientist-softserv/palni-palci/assets/19597776/48740425-8539-40bd-b4d9-676b63ef412e
> 🐛 Fix banner alt text require

- app/parsers/bulkrax/csv_parser_decorator.rb
- config/initializers/bulkrax.rb
- spec/parsers/bulkrax/csv_parser_decorator_spec.rb
This commit will adjust the Bulkrax csv parser fields to allow spaces in the csv headers.  Previously, if you had `rights statement`, this header was not accepted.  With this commit it will be.
Ref:
- https://github.com/scientist-softserv/palni-palci/issues/436
```rb
Bulkrax.config.field_mappings['Bulkrax::CsvParser'] =>
{"abstract"=>{:from=>["abstract"], :split=>"\\|", :generated=>true},
"accessibility_feature"=>
{:from=>["accessibility_feature", "accessibility feature"], :split=>"\\|"},
"accessibility_hazard"=>
{:from=>["accessibility_hazard", "accessibility hazard"], :split=>"\\|"},
"accessibility_summary"=>
{:from=>["accessibility_summary", "accessibility summary"]},
"additional_information"=>
{:from=>["additional_information", "additional information"],
:split=>"\\|", …
```
> 🎁 Make headers with spaces acceptable

- app/helpers/hyku_helper.rb
parent_doc is not a solr document, so calling ['has_model_ssim'] produced and error.
⚠️ I see if we need to contribute this fix back to pals knapsack as well ✅ [**[DONE](https://github.com/samvera/hyku/blob/main/app/helpers/hyku_helper.rb#L30-L42)**]
> :bug: User couldn't edit file sets

- .env
- .github/workflows/build-test-lint.yaml
- .github/workflows/deploy.yaml
- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- docker-compose.yml
- solr/Dockerfile
[Lint](https://github.com/scientist-softserv/palni-palci/actions/runs/8760373124/job/24045383455) step is failing due to some issue with solr
> fix-build-issue

- .github/workflows/deploy.yaml
This was causing an error when deploying pals.
```ruby
"Run sudo rm -rf /usr/share/dotnet && sudo rm -rf /opt/ghc && sudo rm -rf "/usr/local/share/boost" && sudo rm -rf "$AGENT_TOOLSDIRECTORY" /__w/_temp/f7307c65-f24c-404d-a4a2-8e327e69ce19.sh: line 1: sudo: command not found"
```
ref:
- https://github.com/scientist-softserv/palni-palci/actions/runs/8840191966/job/24275038076
- https://github.com/scientist-softserv/actions/compare/remove-sudo-from-setup-env?expand=1
<details>
</details>
> :bug: Revert change to deploy action to remove sudo command - deploy fix

- lib/wings/attribute_transformer_decorator.rb
- lib/wings/model_transformer_decorator.rb
Ref:
- #1026 
Work forms were throwing 504 time out errors because large AdminSets being queried by Hyrax#query_service were loading all of their members.
This fix is a backport of this Hyrax commit:
- https://github.com/samvera/hyrax/commit/75312ee
New work forms throw 504 time out errors in the Grace tenant  
New work forms no longer throw 504 time out errors in the Grace tenant  
This override is no longer needed when Hyrax's version is >= v5.0.1
> i1026 Fix AdminSet-related 504 timeout errors on work forms

- app/parsers/bulkrax/csv_parser_decorator.rb
Ref 
- #1042 
Importing a CSV without a model column leads to the importer failing to run and logging this error: `NameError - uninitialized constant Hyrax::Form Did you mean? Hyrax::Forms`. 
CSVs imported without a model column should fallback on `Bulkrax.default_work_type`.
> i1042 Fall back on default work type when model is empty

- app/controllers/hyrax/my/works_controller_decorator.rb
update the works controller decorator to remove params in collections_service method
https://assaydepot.slack.com/archives/C0313NKC08L/p1721066260232569
A user is reporting an issue depositing works into collections they should have access to (as an admin).
This is on [wabash.hykucommons.org](http://wabash.hykucommons.org/)
Refs #1046 
An admin could not add a work that they searched to a collection from the collection "Adds existing works to collection"
An admin could not add a work they searched for in the my/works page through the "Add to Collection button"
An admin can add a work that they searched to a collection from the collection "Adds existing works to collection"
An admin can add a work they searched for in the my/works page through the "Add to Collection button"
Video of local …
> i1046-admin-can-deposit-works-into-collections-to-main

- app/controllers/catalog_controller.rb
Ref:
- #1051 
- https://github.com/samvera/hyrax/pull/4728
- https://github.com/samvera/hyrax/pull/5937
`:post` has a higher character limit than the default (`:get`)
All pages that query which Collections a user has access to will throw a `RSolr::Error::Http - 414 Request-URI Too Long` error. These include (but may not be limited to):
- Dashboard "All Collections" view 
- Dashboard Collection show page 
- "Add a subcollection" modal populates a list of accessible collections 
- Collection show page (if the user has manage permissions) 
- "Add to collection" modal populates a list of accessible collections 
All pages that query which Collections a user has access to will no longer throw a `RSolr::Error::Http - 414 Request-URI Too Long` error. 
A hotfix for this has been applied to the …
> i1051 Set :post as default Solr HTTP method

- Gemfile.lock
Ref:
- #1053 
This is in response to [CVE-2024-45409](https://nvd.nist.gov/vuln/detail/CVE-2024-45409)
> i1053 update ruby-saml gem version to get security fix

- lib/tasks/tenants.rake
#1063 
Updates the tenants.rake to:
- turn off sentry reporting during the task and then re-enables at the end
- add graceful error handling in order to get the tenants data for client
> i1063-fix-tenants-rake
