app/assets/stylesheets/hyku.scss, app/assets/stylesheets/variables.scss, app/views/splash/index.html.erb
Issue 95 in Gitlab
- fixes nil check bug on splash page
- client requested Avenir font, web font replacement is Montserrat
- client request change in contact email address
- client requested smaller size for h1 font
- client requested same size alignment for left side
- fixes typo
=> client requests, fix nil bug

bin/helm_deploy
see https://github.com/samvera/hyrax/pull/5907
=> bump helm chart to fix sending some requests to workers

.github/workflows/build-test-lint.yaml, .github/workflows/deploy.yaml
debugging deploy by pointing at last deploy release
=> Pin deploy to last release for debugging

bin/helm_deploy
trying to narrow down where the deploy failed
=> debugging deploy

bin/helm_deploy
After merging, need to delete the worker deploy in Rancher before deploying.
=> update helm chart version

app/controllers/concerns/hyrax/works_controller_behavior_decorator.rb
https://github.com/scientist-softserv/palni-palci/issues/283
Param hashes must always have indifferent access to be accepted by hydra-access-controls
=> i283 Params always have indifferent access

ops/staging-deploy.tmpl.yaml, public/500.html
Ref Ticket: https://github.com/scientist-softserv/palni-palci/issues/173
Adds a styled static html 500 error page with:
- the Hyku commons logo
- an error message
- a call to action with email us link
- not styled to any one tenant
- simple but appealing error page
Small video demo to see simple animation: https://share.getcloudapp.com/nOu1plmg
=> I173 add public static 500 error page

.github/workflows/build-test-lint.yaml
Ref ticket: https://github.com/scientist-softserv/dev-ops/issues/498
- updates actions to arm-wrestle branch
=> updates actions to arm-wrestle branch

.github/workflows/build-test-lint.yaml, .github/workflows/deploy.yaml
Ref ticket: https://github.com/scientist-softserv/dev-ops/issues/512
updating the gha to v006
=> i512-update-gha-to-v006

.env, .github/workflows/build-test-lint.yaml, .github/workflows/deploy.yaml
In an effort to get bugs squashed before the holidays we compared what is currently on demo against what is currently on production after resolving some bugs on demo.
These are the only changes that need to get made to main before deploying main to production.
Deployed prod sha on demo: https://share.getcloudapp.com/o0u96J0v
Deployed main on demo: https://share.getcloudapp.com/DOukDPXD
=> Reconcile demo with production

.github/workflows/build-test-lint.yaml, .github/workflows/deploy.yaml
Ref ticket: https://github.com/scientist-softserv/dev-ops/issues/526
Adds cool title for gha actions
=> i526-gc-cool-gha-titles

app/forms/hyrax/etd_form.rb, app/forms/hyrax/generic_work_form.rb, app/forms/hyrax/image_form.rb, app/models/bulkrax/csv_entry_decorator.rb, app/parsers/bulkrax/csv_parser_decorator.rb, app/parsers/bulkrax/oer_csv_parser.rb
ref #404 
Adds Resource Type as a required field to all worktypes. Bulkrax issue where required keys with empty values were considered present.
=> 404 resource type

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
refs https://github.com/scientist-softserv/dev-ops/issues/629.
This PR updates issue and PR templates in this repo.
=> update issue/PR templates

.github/workflows/build-test-lint.yaml, .github/workflows/deploy.yaml
Upgrades the workflow actions to call v0.0.13
=> upgrade-workflows-13

.circleci/config.yml, Gemfile, Gemfile.lock, app/controllers/hyrax/dashboard/collections_controller.rb, app/jobs/reindex_collections_job.rb, config/initializers/hyrax.rb, docker-compose.yml
Ref https://github.com/scientist-softserv/palni-palci/issues/430
`cherry-pick`ed this commit (`57935f95cf9cb0589b5050c30afc55e41fca5993`) from Hyku and resolved the conflicts 
This change should fix the following bug discovered by @ndroark or the production site: 
> When attempting to add an existing work to a collection, the page just spins for 30-45 seconds while submitting the form, ending in a 504 error. A few minutes later, the work shows up in the collection 
Details can be found [here](https://github.com/scientist-softserv/palni-palci/issues/430#issuecomment-1489521409)
=> upgrade to hyrax 3.5, make graph indexer on by default

lib/oai/provider/metadata_format/hyku_dublin_core.rb, spec/features/oai_pmh_spec.rb
Add `<file_url>` tags to custom `oai_hyku` prefix
Refs #423 
No file links display in OAI feed 
Public file links display in OAI feed 
<details>
<summary>Only includes public links</summary>
</details>
=> OAI - add links to public files on works

Gemfile, Gemfile.lock
install a gem useful for debugging
=> install xray-rails

RepoREADME.md
- one update that was useful for me to start the app.
- consistency between sc and dc commands
=> updates to the repo readme

app/forms/hyrax/forms/admin/appearance.rb
- Refs #449
- fix the lint pipeline errors now that the github pipeline is running again
- **does not fix the already broken specs** 
- ref: #466
=> 449 lint fixes

app/helpers/hyrax/iiif_helper_decorator.rb, app/views/hyrax/base/show.html.erb, config/uv/uv-config-no-download.json, package.json
adds custom config.json for the UV
adds the copying of custom jsons to the yarn build package
adds a decorator to passthrough the custom config json based on the `allow_downloads` account setting
=> adds UV config to disable downloads based on Account Setting.

app/helpers/iiif_print/iiif_helper_decorator.rb, app/views/hyrax/base/show.html.erb
changed decorator to the iiif_print one.
=> iiif decorator update

app/views/hyrax/oers/show.html.erb
Fix bug on OER show page where video files were not showing in UV
Refs #456 
<details>
</details>
=> I456 oer viewer

config/authorities/contributing_libraries.yml
Adds the terms/ids for the contributing library controlled vocab
- #511
=> add library names and ids

ops/demo-deploy.tmpl.yaml, ops/production-deploy.tmpl.yaml
Refs https://github.com/scientist-softserv/dev-ops/issues/695
Please read the initial issue linked above
=> 695-update-resource-allocations

Gemfile, Gemfile.lock
=> comment out xray rails

app/views/catalog/_search_form.html.erb, app/views/themes/cultural_repository/catalog/_search_form.html.erb, app/views/themes/institutional_repository/catalog/_search_form.html.erb
adds advanced search to all themes
<details>
<summary>Cultural</summary>
</details>
<details>
<summary>Institutional</summary>
</details>
=> add advanced to the themes

spec/features/advanced_search_spec.rb, spec/models/auth_provider_spec.rb, spec/presenters/hyrax/oer_presenter_spec.rb, spec/search_builders/adv_search_builder_spec.rb
=> fix reshare specs

config/show_themes.yml
Updates the notes for reshare theme
- https://github.com/scientist-softserv/palni-palci/issues/639
Notes should say "For ReShare CDL Pilot use only, do not use unless instructed to do so"
=> Update notes for reshare theme

app/controllers/api/sushi_controller.rb, app/models/sushi.rb, app/models/sushi/platform_report.rb, app/models/sushi/platform_usage_report.rb, spec/models/sushi/platform_report_spec.rb, spec/requests/api/sushi_spec.rb
@jeremyf 
Builds the platform usage report
- #654 
- JSON returned a simple key/value pair
<details>
<summary>JSON</summary>
</details>
=> 654 Platform usage report

app/models/sushi/platform_report.rb, spec/models/sushi/platform_report_spec.rb
Add Platform to report items - missing required key
- #660 
<details>
<summary>Updated JSON</summary>
</details>
=> Platform report rework

app/models/sushi.rb
As part of reading the full Sushi implementation to look for common code, I opted to write some inline documentation for the Sushi module methods.
This is just a bit of tidying up.
=> 📚 Adding inline docs to modules

app/controllers/api/sushi_controller.rb, app/models/sushi.rb, app/models/sushi/item_report.rb, spec/models/sushi/item_report_spec.rb, spec/requests/api/sushi_spec.rb
- we could view the item report for all items
- we can filter the report by a single item
- if the item id given isn't valid, we return a message instead.
<details>
<summary>one item</summary>
http://dev.hyku.test/api/sushi/r51/reports/ir?item_id=181540f4-6e29-496b-8290-211115b1cc8c&begin_date=2023-06&end_date=2023-06
</details>
<details>
<summary>invalid item</summary>
</details>
<details>
<summary>all items</summary>
</details>
=> 627 single item report

app/models/sushi/item_report.rb
4a8fd63cc70fef13c2549179c7f9746a47bbd545
I amended the specs to inject a lot of random data:
```ruby
(1..100).each { |i| (0..60).each { |day| Hyrax::CounterMetric.create!(work_id: "work-id-#{i}", worktype: "GenericWork", resource_type: (i.even? ? "Book" : "Article"), date: day.days.ago.to_date, total_item_investigations: rand(6) + 1, total_item_requests: rand(6) + 1) } }
```
Below is the `Benchmark.measure` of generating the JSON object:
| Scenario                                           | User CPU |  System CPU | User+System |
|----------------------------------------------------|----------|-------------|-------------|
| 100 works without JSON aggregation (e.g. before)   | 0.017059 |  0.002048   |   0.019107  |
| 100 works With JSON aggregation (e.g. now)         | 0.007407 |  0.003174 …
=> ♻️ Reducing # of Rows to Process for Sushi

app/models/sushi.rb, app/models/sushi/item_report.rb, app/models/sushi/platform_report.rb
allow for metric types to be filtered on
- #688 
TODO
=> 688 metric type filter

app/models/sushi/platform_usage_report.rb
Based on #701, in reducing the number of rows we process, we generate
the report faster.
Related to:
- https://github.com/scientist-softserv/palni-palci/pull/701
=> ♻️ Reduce # of Rows to Process for Sushi

Gemfile.lock, db/migrate/20230822142806_add_indices_to_hyrax_counter_metrics.hyrax.rb, db/migrate/20230822142807_add_fields_to_counter_metric.hyrax.rb, db/schema.rb
Adds 4 new fields to the counter metrics table
- #695 
- the fields author, year of publication, title, and publisher have been added to the counter metrics table. 
The is part 1 of ticket #695 - part 2 will include the changes to the import tasks.
=> Update the `Hyrax::CounterMetric` table

app/models/user.rb
References scientist-softserv/palni-palci#584
Paired with @orangewolf 
Made small changes to user model to make uid and display_name more friendly
As part of this PR, the SAML JSON was updated in the admin dashboard
Users can login to PittIR repo on demo with pitt credentials
=> Set up Shibboleth SAML Auth

app/models/sushi.rb, app/models/sushi/item_report.rb, app/models/sushi/platform_report.rb, app/models/sushi/platform_usage_report.rb
- refactor the sushi model so that the coercion methods work the same
- convert each method in the `QueryParametersValidation` module to coercion modules
=> Cohesive sushi model

app/models/sushi/item_report.rb, spec/models/sushi/item_report_spec.rb
allow the `metric_type` query param to actually filter the results
- #688
=> 688-metric-type-filter-v2

config/application.rb
This is covered in the lines above.
=> 🧹 Remove duplication of to_prepare block

app/presenters/hyrax/cdl_presenter.rb, config/locales/blacklight.de.yml, config/locales/blacklight.es.yml, config/locales/blacklight.fr.yml, config/locales/blacklight.it.yml, config/locales/blacklight.pt-BR.yml, config/locales/blacklight.zh.yml, config/locales/cdl.de.yml, config/locales/cdl.es.yml, config/locales/cdl.fr.yml, config/locales/cdl.it.yml, config/locales/cdl.pt-BR.yml, config/locales/cdl.zh.yml, config/locales/de.yml, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/hyrax.de.yml, config/locales/hyrax.en.yml, config/locales/hyrax.es.yml, config/locales/hyrax.fr.yml, config/locales/hyrax.it.yml, config/locales/hyrax.pt-BR.yml, config/locales/hyrax.zh.yml, config/locales/it.yml, config/locales/pt-BR.yml, config/locales/zh.yml, spec/features/create_etd_spec.rb, spec/features/create_oer_spec.rb
Refs #268 
The acronym work types (OER, ETD, CDL) were not upper cased in certain areas of the application.
Upper cased the acronym work types.
Before | After
---------|----------
=> I268 update work type labels

config/authorities/resource_types.yml
This commit expands the options of resource types. It is listed in alphabetical order.
Refs #741 
Before there were no options for 
There are options for
=> :gift: i741 - Add resource types to local controlled vocabulary

app/services/generate_counter_metrics.rb
Related to:
- https://github.com/scientist-softserv/palni-palci/issues/721
- https://github.com/scientist-softserv/palni-palci/pull/771
=> 🐛 Add multi-author coercion for generate counter metrics

app/models/sushi.rb, app/models/sushi/error.rb, app/models/sushi/item_report.rb, app/models/sushi/platform_report.rb, app/models/sushi/platform_usage_report.rb, spec/models/sushi/item_report_spec.rb, spec/models/sushi/platform_report_spec.rb, spec/models/sushi/platform_usage_report_spec.rb
validate the parameters given to the reports
- #688 
- you could pass an invalid parameter and the report would render
- if you pass an invalid parameter, a 3050 exception error will be rendered
=> 688 exception 3050

app/views/hyrax/base/show.html.erb, app/views/hyrax/oers/show.html.erb, app/views/themes/cultural_show/hyrax/base/show.html.erb, app/views/themes/cultural_show/hyrax/oers/show.html.erb, app/views/themes/image_show/hyrax/base/show.html.erb, app/views/themes/scholarly_show/hyrax/base/show.html.erb, app/views/themes/scholarly_show/hyrax/oers/show.html.erb
We are disabling the analytics button until a future fix is working.
Issue:
- https://github.com/scientist-softserv/palni-palci/issues/838
=> :gift: disable analytics button

app/views/shared/_footer.html.erb
This commit will ad a link to the privacy policy in the footer.
Ref:
- https://github.com/scientist-softserv/palni-palci/issues/822
=> 🎁 Add Privacy Policy link to footer

ops/demo-deploy.tmpl.yaml
This commit will add the user's default password to demo environment.
Ref:
- https://github.com/scientist-softserv/palni-palci/issues/446
=> 🧹 Add user's default password to demo

app/views/hyrax/base/_relationships.html.erb, app/views/themes/cultural_show/hyrax/base/_relationships.html.erb
This commit will add the `Part of` section to the show page for non-users. It will also add the `Part of` section show up on the cultural theme.
Ref:
- https://github.com/scientist-softserv/palni-palci/issues/840
=> 🐛 Make `Part of` show for non-users

config/locales/de.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/it.yml, config/locales/pt-BR.yml, config/locales/simple_form.en.yml, config/locales/zh.yml
Follow up for https://github.com/scientist-softserv/palni-palci/issues/446
This will translate the Activate button that was added. PR: https://github.com/scientist-softserv/palni-palci/pull/858
=> Run translations for activate user btn

app/controllers/hyrax/my/works_controller_decorator.rb, app/helpers/blacklight/configuration_helper_behavior_decorator.rb
This commit adds and updates comments for our future selves.
=> 📚 Add and update comments

app/indexers/app_indexer.rb, app/indexers/collection_indexer.rb
Fix misspelling of depositor so sort works
Refs
- https://github.com/scientist-softserv/palni-palci/issues/748
<details>
</details>
Requires a reindex of both works and collections
=>  🐛 Fix misspelling on depositor

app/controllers/hyrax/homepage_controller.rb, app/views/_user_util_links.html.erb, app/views/shared/_footer.html.erb, app/views/themes/cultural_repository/_user_util_links.html.erb, app/views/themes/institutional_repository/_user_util_links.html.erb, config/features.rb, spec/views/themes/cultural_repository/_user_util_links.html.erb_spec.rb, spec/views/themes/institutional_repository/_user_util_links.html.erb_spec.rb, spec/views/themes/reshare_show/_user_util_links.html.erb_rspec.rb
Adds a feature flipper for "show login" with a default value of true
Modifies top right links based on a combination of admin rights, show page theme, and feature flipper.
Adds specs for all versions of user_util_links menus to track variations
Refs https://github.com/scientist-softserv/palni-palci/issues/891
Full links available on all pages except with reshare show page theme
Reshare show page theme links only appear to logged in admin
With Feature Flipper `on`, top right dropdown menu shows as normal: 
- reshare show page theme does not show login option
- all other themes and pages show normally
With Feature Flipper `off`, top right dropdown menu never shows login option on any page
<details>
<summary>Screenshots</summary>
</details>
=> 🎁 Restrict login links via feature flipper

app/forms/hyrax/cdl_form.rb, app/models/cdl.rb, app/presenters/hyku/work_show_presenter.rb, app/views/hyrax/base/show.html.erb
Adds video embed to CDL work type.
Issue:
=> 🎁 i911 Video Embed: CDL Work Type

lib/omni_auth/strategies/open_id_connect_decorator.rb
=> Skip validation on reshare openid adapter for now

ops/demo-deploy.tmpl.yaml, ops/production-deploy.tmpl.yaml
we do not use them and they cost $
=> do not make a load balancer for each and every nginx service

app/forms/video_embed_form_behavior.rb
Remove video embed from primary terms
Refs
=> 🧹 remove video_embed from primary terms

spec/models/site_spec.rb
Code was updated in a hot fix but the specs were not, thus causing failures.
Issue:
- https://github.com/scientist-softserv/palni-palci/issues/915
=> correct failing spec

ops/production-deploy.tmpl.yaml
Fixes [this error](https://github.com/scientist-softserv/palni-palci/actions/runs/8104721777/job/22151846081) when deploying PALs prod.
Prod deploy fails 
Prod deploy succeeds
=> fix uppercase yaml key (and value)

app/views/themes/image_show/hyrax/base/show.html.erb, app/views/themes/scholarly_show/hyrax/oers/show.html.erb
Continues https://github.com/scientist-softserv/palni-palci/issues/958
Refs https://github.com/scientist-softserv/palni-palci/pull/983
Several other show views have missing descriptions in a few situations.
All show pages should show description regardless of type of media.
=> Add more missing descriptions

app/assets/stylesheets/hyku.scss
Ref:
- https://github.com/scientist-softserv/palni-palci/issues/830
=> 🧹 Reduce margin-bottom on properitor splash page

.github/workflows/build-test-lint.yaml, .github/workflows/deploy.yaml, Dockerfile, Gemfile, Gemfile.lock, README.md, app/controllers/users/omniauth_callbacks_controller.rb, app/jobs/create_large_derivatives_job.rb, app/models/sushi.rb, app/models/sushi/platform_report.rb, app/models/work_authorization.rb, app/presenters/hyrax/collection_presenter_decorator.rb, app/services/iiif_print/tenant_config.rb, config/application.rb, docker-compose.yml, lib/hyrax/controlled_vocabularies/location_decorator.rb, lib/omni_auth/strategies/open_id_connect_decorator.rb, lib/tasks/move_banner_images.rake, spec/features/feature_flag_spec.rb
Primarily solved using:
```bash
rg --hidden --files-with-matches --glob '!.git/**' "softserv" | xargs sed -i .bak 's/scientist-softserv/notch8/g'
```
=> Update GitHub Org (SoftServ => Notch8)
